<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AsmaulHusnaTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $asmaulHusnas = [
            [
                'arabic_name'  => 'الله',
                'bangla_name'  => 'আল্লাহ',
                'english_name' => 'Allah',
                'meaning'      => 'আল্লাহ',
                'description'  => 'আল্লাহর সকল নামের মধ্যে সবচেয়ে বড় নাম',
            ],
            [
                'arabic_name'  => 'الرحمن',
                'bangla_name'  => 'আর রহমান',
                'english_name' => 'Ar-Rahman',
                'meaning'      => 'অতি দয়ালু',
                'description'  => 'যিনি সকল সৃষ্টির উপর তাঁর দয়া বর্ষাতে থাকেন।',
            ],
            [
                'arabic_name'  => 'الرحيم',
                'bangla_name'  => 'আর রহীম',
                'english_name' => 'Ar-Rahim',
                'meaning'      => 'অতি দয়ালু',
                'description'  => 'যিনি সকল সৃষ্টির উপর তাঁর দয়া বর্ষাতে থাকেন।',
            ],
            [
                'arabic_name'  => 'الملك',
                'bangla_name'  => 'আল মালিক',
                'english_name' => 'Al-Malik',
                'meaning'      => 'সর্বশক্তিমান',
                'description'  => 'যিনি সকল সৃষ্টির উপর তাঁর দয়া বর্ষাতে থাকেন।',
            ],
            [
                'arabic_name'  => 'القدوس',
                'bangla_name'  => 'আল কুদ্দুস',
                'english_name' => 'Al-Quddus',
                'meaning'      => 'পবিত্র',
                'description'  => 'যিনি সকল সৃষ্টির উপর তাঁর দয়া বর',
            ],
            [
                'arabic_name'  => 'السلام',
                'bangla_name'  => 'আস সালাম',
                'english_name' => 'As-Salam',
                'meaning'      => 'শান্তির সৃষ্টিকর্তা',
                'description'  => 'যিনি সকল সৃষ্টির উপর তাঁর দয়া বর্ষাতে থাকেন।',
            ],
            [
                'arabic_name'  => 'المؤمن',
                'bangla_name'  => 'আল মুমিন',
                'english_name' => 'Al-Mu\'min',
                'meaning'      => 'ঈমানদারদের নিরাপদ রক্ষক',
                'description'  => 'যিনি সকল সৃষ্টির উপর তাঁর দয়া বর্ষাতে থাকেন।',
            ],
            [
                'arabic_name'  => 'المهيمن',
                'bangla_name'  => 'আল মুহাইমিন',
                'english_name' => 'Al-Muhaymin',
                'meaning'      => 'সকল সৃষ্টির নিরাপদ রক্ষক ও পরিচালক',
                'description'  => 'যিনি সকল সৃষ্টির উপর তাঁর দয়া বর',
            ],
            [
                'arabic_name'  => 'العزيز',
                'bangla_name'  => 'আল আজিজ',
                'english_name' => 'Al-Aziz',
                'meaning'      => 'অতি শক্তিশালী ও অবিচল',
                'description'  => 'যিনি সকল সৃষ্টির উপর তাঁর দয়া ব',
            ],
            [
                'arabic_name'  => 'الجبار',
                'bangla_name'  => 'আল জাব্বার',
                'english_name' => 'Al-Jabbar',
                'meaning'      => 'সকল সৃষ্টির উপর পরাজিত করার ক্ষমতা ও শক্তি যিনি পালন করেন।',
                'description'  => 'যিনি সকল সৃষ্টির উপর পরাজিত করার ক্ষমতা ও শক্তি যিনি পালন করেন।',
            ],
            [
                'arabic_name'  => 'المتكبر',
                'bangla_name'  => 'আল মুতাকাব্বির',
                'english_name' => 'Al-Mutakabbir',
                'meaning'      => 'অতি মহান ও অতিশ্রেষ্ঠ',
                'description'  => 'যিনি সকল সৃষ্টির উপর পরাজিত করার ক্ষমতা ও শক্তি যিনি পালন করেন',
            ],
            [
                'arabic_name'  => 'الخالق',
                'bangla_name'  => 'আল খালিক',
                'english_name' => 'Al-Khaliq',
                'meaning'      => 'সকল সৃষ্টির সৃষ্টিকর্তা',
                'description'  => 'যিনি সকল সৃষ্টির সৃষ্টিকর্তা',
            ],
            [
                'arabic_name'  => 'البارئ',
                'bangla_name'  => 'আল বারি',
                'english_name' => 'Al-Bari\'',
                'meaning'      => 'সকল সৃষ্টির সৃষ্টিকর্তা',
                'description'  => 'যিনি সকল সৃষ্টির সৃষ্টিকর্তা',
            ],
            [
                'arabic_name'  => 'المصور',
                'bangla_name'  => 'আল মুসাওয়ীর',
                'english_name' => 'Al-Musawwir',
                'meaning'      => 'সকল সৃষ্টির সৃষ্টিকর্তা',
                'description'  => 'যিনি সকল সৃষ্টির সৃষ্টিকর্তা',
            ],
            [
                'arabic_name'  => 'الغفار',
                'bangla_name'  => 'আল গাফফার',
                'english_name' => 'Al-Ghaffar',
                'meaning'      => 'অতি ক্ষমাশীল',
                'description'  => 'যিনি সকল সৃষ্টির সৃষ্টিকর্তা',
            ],
            [
                'arabic_name'  => 'القهار',
                'bangla_name'  => 'আল কাহার',
                'english_name' => 'Al-Qahhar',
                'meaning'      => 'সকল সৃষ্টির উপর পরাজিত করার ক্ষমতা ও শক্তি যিনি পালন করেন',
                'description'  => 'যিনি সকল সৃষ্টির উপর পরাজিত করার ক্ষমতা ও শক্তি যিনি পালন করেন',
            ],
            [
                'arabic_name'  => 'الوهاب',
                'bangla_name'  => 'আল ওয়াহ্হাব',
                'english_name' => 'Al-Wahhab',
                'meaning'      => 'অতি দাতা ও উদার',
                'description'  => 'যিনি সকল সৃষ্টির উপর পরাজিত করার ক্ষমতা ও শক্তি যিনি পালন করেন',
            ],
            [
                'arabic_name'  => 'الرزاق',
                'bangla_name'  => 'আর রজ্জাক',
                'english_name' => 'Ar-Razzaq',
                'meaning'      => 'সকল সৃষ্টির উপর পরাজিত করার ক্ষমতা ও শক্তি যিনি পালন করেন',
                'description'  => 'যিনি সকল সৃষ্টির উপর পরাজিত করার ক্ষমতা ও শক্তি যিনি পালন করেন',

            ],
            [
                'arabic_name'  => 'الفتاح',
                'bangla_name'  => 'আল ফাত্তাহ',
                'english_name' => 'Al-Fattah',
                'meaning'      => 'সকল সৃষ্টির উপর পরাজিত করার ক্ষমতা ও শক্তি যিনি পালন করেন',
                'description'  => 'যিনি সকল সৃষ্টির উপর পরাজিত করার ক্ষমতা ও শক্তি যিনি পালন করেন',
            ],
            [
                'arabic_name'  => 'العليم',
                'bangla_name'  => 'আল আলীম',
                'english_name' => 'Al-\'Alim',
                'meaning'      => 'সকল সৃষ্টির উপর পরাজিত করার ক্ষমতা ও শক্তি যিনি পালন করেন',
                'description'  => 'যিনি সকল সৃষ্টির উপর পরাজিত করার ক্ষমতা ও শক্তি যিনি পালন করেন',
            ],
            [
                'arabic_name'  => 'القابض',
                'bangla_name'  => 'আল কাবিদ',
                'english_name' => 'Al-Qabid',
                'meaning'      => 'সকল সৃষ্টির উপর পরাজিত কর',
                'description'  => 'যিনি সকল সৃষ্টির উপর পরাজিত কারী ও শক্তিশালী',
            ],
            [
                'arabic_name'  => 'الباسط',
                'bangla_name'  => 'আল বাসিত',
                'english_name' => 'Al-Basit',
                'meaning'      => 'সকল সৃষ্টির উপর পরাজিত করার ক্ষমতা ও শক্তি যিনি পালন করেন',
                'description'  => 'যিনি সকল সৃষ্টির উপর পরাজিত করার ক্ষমতা ও শক্তি যিনি পালন করেন',
            ],
            [
                'arabic_name'  => 'الخافض',
                'bangla_name'  => 'আল খাফিদ',
                'english_name' => 'Al-Khafid',
                'meaning'      => 'অতি নিম্ন করেন',
                'description'  => 'যিনি সকল সৃষ্টির উপর পরাজিত করার ক্ষমতা ও শক্তি যিনি পালন করেন',
            ],
            [
                'arabic_name'  => 'الرافع',
                'bangla_name'  => 'আর রাফিও',
                'english_name' => 'Ar-Rafi\'',
                'meaning'      => 'অতি উচ্চ করেন',
                'description'  => 'যিনি সকল সৃষ্টির উপর পরাজিত করার ক্ষমতা ও শক্তি যিনি পালন',
            ],
            [
                'arabic_name'  => 'المعز',
                'bangla_name'  => 'আল মুইজ্জ',
                'english_name' => 'Al-Mu\'izz',
                'meaning'      => 'অতি মান দেন',
                'description'  => 'যিনি সকল সৃষ্টির উপর পরাজিত করার ক্ষমতা ও শক্তি যিনি পালন করেন',
            ],
            [
                'arabic_name'  => 'المذل',
                'bangla_name'  => 'আল মুদ্দিল',
                'english_name' => 'Al-Mudhill',
                'meaning'      => 'অতি নীচ করেন',
                'description'  => 'যিনি সকল সৃষ্টির উপর পরাজিত করার ক্ষমতা ও শক্তি যিনি পালন করেন',
            ],
            [
                'arabic_name'  => 'السميع',
                'bangla_name'  => 'আস সামী',
                'english_name' => 'As-Sami\'',
                'meaning'      => 'সকল কিছু শুনেন',
                'description'  => 'যিনি সকল কিছু শুনেন এবং সকল কিছু জানেন',
            ],
            [
                'arabic_name'  => 'البصير',
                'bangla_name'  => 'আল বাসীর',
                'english_name' => 'Al-Basir',
                'meaning'      => 'সকল কিছু দেখেন',
                'description'  => 'যিনি সকল কিছু দেখেন এবং সকল কিছু জানেন',
            ],
            [
                'arabic_name'  => 'الحكم',
                'bangla_name'  => 'আল হাকাম',
                'english_name' => 'Al-Hakam',
                'meaning'      => 'সকল কিছু নির্ণয় করেন',
                'description'  => 'যিনি সকল কিছু নির্ণয় করেন',
            ],
            [
                'arabic_name'  => 'العدل',
                'bangla_name'  => 'আল আদিল',
                'english_name' => 'Al-\'Adl',
                'meaning'      => 'অতি ন্যায়বাদী',
                'description'  => 'যিনি সকল কিছু নির্ণয় করেন',
            ],
            [
                'arabic_name'  => 'اللطيف',
                'bangla_name'  => 'আল লাতীফ',
                'english_name' => 'Al-Latif',
                'meaning'      => 'অতি সুক্ষ্মমনা',
                'description'  => 'যিনি সকল কিছু নির্ণয় করেন',
            ],
            [
                'arabic_name'  => 'الخبير',
                'bangla_name'  => 'আল খাবীর',
                'english_name' => 'Al-Khabir',
                'meaning'      => 'সকল কিছু জানেন',
                'description'  => 'যিনি সকল কিছু জানেন',
            ],
            [
                'arabic_name'  => 'الحليم',
                'bangla_name'  => 'আল হালীম',
                'english_name' => 'Al-Halim',
                'meaning'      => 'অতি ধৈর্যশীল',
                'description'  => 'যিনি সকল কিছু জানেন',
            ],
            [
                'arabic_name'  => 'العظيم',
                'bangla_name'  => 'আল আজীম',
                'english_name' => 'Al-Azim',
                'meaning'      => 'অতি মহান',
                'description'  => 'যিনি সকল কিছু জানেন',
            ],
            [
                'arabic_name'  => 'الغفور',
                'bangla_name'  => 'আল গাফূর',
                'english_name' => 'Al-Ghafur',
                'meaning'      => 'অতি ক্ষমাশীল',
                'description'  => 'যিনি সকল কিছু জানেন',
            ],
            [
                'arabic_name'  => 'الشكور',
                'bangla_name'  => 'আস শাকূর',
                'english_name' => 'Ash-Shakur',
                'meaning'      => 'অতি কৃতজ্ঞ',
                'description'  => 'যিনি সকল কিছু জানেন',
            ],
            [
                'arabic_name'  => 'العلي',
                'bangla_name'  => 'আল আলী',
                'english_name' => 'Al-Ali',
                'meaning'      => 'অতি উচ্চ',
                'description'  => 'যিনি সকল কিছু জানেন',
            ],
            [
                'arabic_name'  => 'الكبير',
                'bangla_name'  => 'আল কাবীর',
                'english_name' => 'Al-Kabir',
                'meaning'      => 'অতি মহান',
                'description'  => 'যিনি সকল কিছু জানেন',
            ],
            [
                'arabic_name'  => 'الحفيظ',
                'bangla_name'  => 'আল হাফিজ',
                'english_name' => 'Al-Hafiz',
                'meaning'      => 'সকল কিছু রক্ষা করেন',
                'description'  => 'যিনি সকল কিছু জানেন',
            ],
            [
                'arabic_name'  => 'المقيت',
                'bangla_name'  => 'আল মুকীত',
                'english_name' => 'Al-Muqit',
                'meaning'      => 'সকল কিছু পুষ্টি করেন',
                'description'  => 'যিনি সকল কিছু জানেন',
            ],
            [
                'arabic_name'  => 'الحسيب',
                'bangla_name'  => 'আল হাসীব',
                'english_name' => 'Al-Hasib',
                'meaning'      => 'সকল কিছু হিসাব করেন',
                'description'  => 'যিনি সকল কিছু জানেন',
            ],
            [
                'arabic_name'  => 'الجليل',
                'bangla_name'  => 'আল জালীল',
                'english_name' => 'Al-Jalil',
                'meaning'      => 'অতি মহান',
                'description'  => 'যিনি সকল কিছু জানেন',
            ],
            [
                'arabic_name'  => 'الكريم',
                'bangla_name'  => 'আল কারীম',
                'english_name' => 'Al-Karim',
                'meaning'      => 'অতি মহান',
                'description'  => 'যিনি সকল কিছু জানেন',
            ],
            [
                'arabic_name'  => 'الرقيب',
                'bangla_name'  => 'আর রাকীব',
                'english_name' => 'Ar-Raqib',
                'meaning'      => 'সকল কিছু দেখেন',
                'description'  => 'যিনি সকল কিছু জানেন',
            ],
            [
                'arabic_name'  => 'المجيب',
                'bangla_name'  => 'আল মুজীব',
                'english_name' => 'Al-Mujib',
                'meaning'      => 'সকল কিছু প্রতিদান করেন',
                'description'  => 'যিনি সকল কিছু জানেন',
            ],
            [
                'arabic_name'  => 'الواسع',
                'bangla_name'  => 'আল ওয়াসিউ',
                'english_name' => 'Al-Wasi\'',
                'meaning'      => 'অতি বিস্তৃত',
                'description'  => 'যিনি সকল কিছু জানেন',
            ],
            [
                'arabic_name'  => 'الحكيم',
                'bangla_name'  => 'আল হাকীম',
                'english_name' => 'Al-Hakim',
                'meaning'      => 'অতি বুদ্ধিমান',
                'description'  => 'যিনি সকল কিছু জানেন',
            ],
            [
                'arabic_name'  => 'الودود',
                'bangla_name'  => 'আল ওয়াদুদ',
                'english_name' => 'Al-Wadud',
                'meaning'      => 'অতি দয়ালু',
                'description'  => 'যিনি সকল কিছু জানেন',
            ],
            [
                'arabic_name'  => 'المجيد',
                'bangla_name'  => 'আল মাজীদ',
                'english_name' => 'Al-Majid',
                'meaning'      => 'অতি মহান',
                'description'  => 'যিনি সকল কিছু জানেন',
            ],
            [
                'arabic_name'  => 'الباعث',
                'bangla_name'  => 'আল বাইস',
                'english_name' => 'Al-Ba\'ith',
                'meaning'      => 'সকল কিছু পুনরুত্থান করেন',
                'description'  => 'যিনি সকল কিছু জানেন',
            ],
            [
                'arabic_name'  => 'الشهيد',
                'bangla_name'  => 'আশ শাহীদ',
                'english_name' => 'Ash-Shahid',
                'meaning'      => 'সকল কিছু দেখেন',
                'description'  => 'যিনি সকল কিছু জানেন',
            ],
            [
                'arabic_name'  => 'الحق',
                'bangla_name'  => 'আল হাক',
                'english_name' => 'Al-Haqq',
                'meaning'      => 'সত্য',
                'description'  => 'যিনি সকল কিছু জানেন',
            ],
            [
                'arabic_name'  => 'الوكيل',
                'bangla_name'  => 'আল ওয়াকীল',
                'english_name' => 'Al-Wakil',
                'meaning'      => 'সকল কিছু নির্ভর করেন',
                'description'  => 'যিনি সকল কিছু জানেন',
            ],
            [
                'arabic_name'  => 'القوى',
                'bangla_name'  => 'আল কাওয়ী',
                'english_name' => 'Al-Qawiyy',
                'meaning'      => 'অতি শক্তিশালী',
                'description'  => 'যিনি সকল কিছু জানেন',
            ],
            [
                'arabic_name'  => 'المتين',
                'bangla_name'  => 'আল মাতীন',
                'english_name' => 'Al-Matin',
                'meaning'      => 'অতি দৃঢ়',
                'description'  => 'যিনি সকল কিছু জানেন',
            ],
            [
                'arabic_name'  => 'الولى',
                'bangla_name'  => 'আল ওয়ালী',
                'english_name' => 'Al-Waliyy',
                'meaning'      => 'অতি প্রিয়',
                'description'  => 'যিনি সকল কিছু জানেন',
            ],
            [
                'arabic_name'  => 'الحميد',
                'bangla_name'  => 'আল হামীদ',
                'english_name' => 'Al-Hamid',
                'meaning'      => 'অতি প্রশংসনীয়',
                'description'  => 'যিনি সকল কিছু জানেন',
            ],
            [
                'arabic_name'  => 'المحصى',
                'bangla_name'  => 'আল মুহসী',
                'english_name' => 'Al-Muhsi',
                'meaning'      => 'সকল কিছু হিসাব করেন',
                'description'  => 'যিনি সকল কিছু জানেন',
            ],
            [
                'arabic_name'  => 'المبدئ',
                'bangla_name'  => 'আল মুবদী',
                'english_name' => 'Al-Mubdi',
                'meaning'      => 'সকল কিছু সৃষ্টি করেন',
                'description'  => 'যিনি সকল কিছু জানেন',
            ],
            [
                'arabic_name'  => 'المعيد',
                'bangla_name'  => 'আল মুইদ',
                'english_name' => 'Al-Muid',
                'meaning'      => 'সকল কিছু পুনরুত্থান করেন',
                'description'  => 'যিনি সকল কিছু জানেন',
            ],
            [
                'arabic_name'  => 'المحيى',
                'bangla_name'  => 'আল মুহী',
                'english_name' => 'Al-Muhyi',
                'meaning'      => 'সকল কিছু জীবন দান করেন',
                'description'  => 'যিনি সকল কিছু জানেন',
            ],
            [
                'arabic_name'  => 'المميت',
                'bangla_name'  => 'আল মুমীত',
                'english_name' => 'Al-Mumit',
                'meaning'      => 'সকল কিছু মৃত্যু দান করেন',
                'description'  => 'যিনি সকল কিছু জানেন',
            ],
            [
                'arabic_name'  => 'الحي',
                'bangla_name'  => 'আল হাইয়',
                'english_name' => 'Al-Hayy',
                'meaning'      => 'অতি জীবনী',
                'description'  => 'যিনি সকল কিছু জানেন',
            ],
            [
                'arabic_name'  => 'القيوم',
                'bangla_name'  => 'আল কাইয়ুম',
                'english_name' => 'Al-Qayyum',
                'meaning'      => 'সকল কিছু পালন করেন',
                'description'  => 'যিনি সকল কিছু জানেন',
            ],
            [
                'arabic_name'  => 'الواجد',
                'bangla_name'  => 'আল ওয়াজিদ',
                'english_name' => 'Al-Wajid',
                'meaning'      => 'সকল কিছু পাওয়া যায়',
                'description'  => 'যিনি সকল কিছু জানেন',
            ],
            [
                'arabic_name'  => 'الماجد',
                'bangla_name'  => 'আল মাজিদ',
                'english_name' => 'Al-Majid',
                'meaning'      => 'অতি মহান',
                'description'  => 'যিনি সকল কিছু জানেন',
            ],
            [
                'arabic_name'  => 'الواحد',
                'bangla_name'  => 'আল ওয়াহিদ',
                'english_name' => 'Al-Wahid',
                'meaning'      => 'একমাত্র',
                'description'  => 'যিনি সকল কিছু জানেন',
            ],
            [
                'arabic_name'  => 'الصمد',
                'bangla_name'  => 'আস সামাদ',
                'english_name' => 'As-Samad',
                'meaning'      => 'যিনি কাউকে নির্ভর করেন না এবং সকল কিছু নির্ভর করেন',
                'description'  => 'যিনি সকল কিছু জানেন',
            ],
            [
                'arabic_name'  => 'القادر',
                'bangla_name'  => 'আল কাদির',
                'english_name' => 'Al-Qadir',
                'meaning'      => 'অতি শক্তিশালী',
                'description'  => 'যিনি সকল কিছু জানেন',
            ],
            [
                'arabic_name'  => 'المقتدر',
                'bangla_name'  => 'আল মুকতাদির',
                'english_name' => 'Al-Muqtadir',
                'meaning'      => 'অতি শক্তিশালী',
                'description'  => 'যিনি সকল কিছু জানেন',
            ],
            [
                'arabic_name'  => 'المقدم',
                'bangla_name'  => 'আল মুকাদ্দিম',
                'english_name' => 'Al-Muqaddim',
                'meaning'      => 'সকল কিছু অগ্রাধিকার দেন',
                'description'  => 'যিনি সকল কিছু জানেন',
            ],
            [
                'arabic_name'  => 'المؤخر',
                'bangla_name'  => 'আল মুআখখির',
                'english_name' => 'Al-Muakhkhir',
                'meaning'      => 'সকল কিছু পিছনে ফেলেন',
                'description'  => 'যিনি সকল কিছু জানেন',
            ],
            [
                'arabic_name'  => 'الأول',
                'bangla_name'  => 'আল আউয়াল',
                'english_name' => 'Al-Awwal',
                'meaning'      => 'প্রথম ও শুরুতে থাকেন',
                'description'  => 'যিনি সকল কিছু জানেন',
            ],
            [
                'arabic_name'  => 'الأخر',
                'bangla_name'  => 'আল আখির',
                'english_name' => 'Al-Akhir',
                'meaning'      => 'শেষে থাকেন',
                'description'  => 'যিনি সকল কিছু জানেন',
            ],
            [
                'arabic_name'  => 'الظاهر',
                'bangla_name'  => 'আল জাহির',
                'english_name' => 'Az-Zahir',
                'meaning'      => 'সকল কিছু প্রকাশ করেন',
                'description'  => 'যিনি সকল কিছু জানেন',
            ],
            [
                'arabic_name'  => 'الباطن',
                'bangla_name'  => 'আল বাতিন',
                'english_name' => 'Al-Batin',
                'meaning'      => 'সকল কিছু গোপন করেন',
                'description'  => 'যিনি সকল কিছু জানেন',
            ],
            [
                'arabic_name'  => 'الوالي',
                'bangla_name'  => 'আল ওয়ালী',
                'english_name' => 'Al-Wali',
                'meaning'      => 'অতি প্রিয়',
                'description'  => 'যিনি সকল কিছু জানেন',
            ],
            [
                'arabic_name'  => 'المتعالي',
                'bangla_name'  => 'আল মুতাআলী',
                'english_name' => 'Al-Muta\'ali',
                'meaning'      => 'অতি উচ্চ ও মহান',
                'description'  => 'যিনি সকল কিছু জানেন',
            ],
            [
                'arabic_name'  => 'البر',
                'bangla_name'  => 'আল বারর',
                'english_name' => 'Al-Barr',
                'meaning'      => 'অতি দানশীল',
                'description'  => 'যিনি সকল কিছু জানেন',
            ],
            [
                'arabic_name'  => 'التواب',
                'bangla_name'  => 'আত তাওয়াব',
                'english_name' => 'At-Tawwab',
                'meaning'      => 'অতি প্রতিশোধ গ্রহণ করেন',
                'description'  => 'যিনি সকল কিছু জানেন',
            ],
            [
                'arabic_name'  => 'المنتقم',
                'bangla_name'  => 'আল মুনতাকিম',
                'english_name' => 'Al-Muntaqim',
                'meaning'      => 'অতি প্রতিশোধ গ্রহণ করেন',
                'description'  => 'যিনি সকল কিছু জানেন',
            ],
            [
                'arabic_name'  => 'العفو',
                'bangla_name'  => 'আল আফুও',
                'english_name' => 'Al-Afuw',
                'meaning'      => 'অতি ক্ষমাশীল',
                'description'  => 'যিনি সকল কিছু জানেন',
            ],
            [
                'arabic_name'  => 'الرؤوف',
                'bangla_name'  => 'আর রুফ',
                'english_name' => 'Ar-Ra\'uf',
                'meaning'      => 'অতি দয়ালু',
                'description'  => 'যিনি সকল কিছু জানেন',
            ],
            [
                'arabic_name'  => 'مالك الملك',
                'bangla_name'  => 'মালিকুল মুলক',
                'english_name' => 'Malik-ul-Mulk',
                'meaning'      => 'সকল রাজ্যের মালিক',
                'description'  => 'যিনি সকল কিছু জানেন',
            ],
            [
                'arabic_name'  => 'ذو الجلال والإكرام',
                'bangla_name'  => 'যুযুল জালালি ওয়াল ইকরাম',
                'english_name' => 'Dhu-l-Jalali wa-l-Ikram',
                'meaning'      => 'মহান ও মহান সম্মানী',
                'description'  => 'যিনি সকল কিছু জানেন',
            ],
            [
                'arabic_name'  => 'المقسط',
                'bangla_name'  => 'আল মুকসিত',
                'english_name' => 'Al-Muqsit',
                'meaning'      => 'অতি ন্যায়বাদী',
                'description'  => 'যিনি সকল কিছু জানেন',
            ],
            [
                'arabic_name'  => 'الجامع',
                'bangla_name'  => 'আল জামeই',
                'english_name' => 'Al-Jami\'',
                'meaning'      => 'সকল কিছু সংগ্রহ করেন',
                'description'  => 'যিনি সকল কিছু জানেন',
            ],
            [
                'arabic_name'  => 'الغنى',
                'bangla_name'  => 'আল গানী',
                'english_name' => 'Al-Ghani',
                'meaning'      => 'অতি সমৃদ্ধ',
                'description'  => 'যিনি সকল কিছু জানেন',
            ],
            [
                'arabic_name'  => 'المغنى',
                'bangla_name'  => 'আল মুগনী',
                'english_name' => 'Al-Mughni',
                'meaning'      => 'সকল কিছু সমৃদ্ধি দান করেন',
                'description'  => 'যিনি সকল কিছু জানেন',
            ],
            [
                'arabic_name'  => 'المانع',
                'bangla_name'  => 'আল মানিউ',
                'english_name' => 'Al-Mani\'',
                'meaning'      => 'সকল কিছু প্রতিরোধ করেন',
                'description'  => 'যিনি সকল কিছু জানেন',
            ],
            [
                'arabic_name'  => 'الضار',
                'bangla_name'  => 'আদ দারু',
                'english_name' => 'Ad-Darr',
                'meaning'      => 'সকল কিছু ক্ষতি দান করেন',
                'description'  => 'যিনি সকল কিছু জানেন',
            ],
            [
                'arabic_name'  => 'النافع',
                'bangla_name'  => 'আন নাফিউ',
                'english_name' => 'An-Nafi\'',
                'meaning'      => 'সকল কিছু লাভ দান করেন',
                'description'  => 'যিনি সকল কিছু জানেন',
            ],
            [
                'arabic_name'  => 'النور',
                'bangla_name'  => 'আন নূর',
                'english_name' => 'An-Nur',
                'meaning'      => 'অতি জ্যোতি',
                'description'  => 'যিনি সকল কিছু জানেন',
            ],
            [
                'arabic_name'  => 'الهادى',
                'bangla_name'  => 'আল হাদী',
                'english_name' => 'Al-Hadi',
                'meaning'      => 'সকল কিছু পথ দেখান',
                'description'  => 'যিনি সকল কিছু জানেন',
            ],
            [
                'arabic_name'  => 'البديع',
                'bangla_name'  => 'আল বাদী',
                'english_name' => 'Al-Badi\'',
                'meaning'      => 'অতি অদ্ভুত',
                'description'  => 'যিনি সকল কিছু জানেন',
            ],
            [
                'arabic_name'  => 'الباقى',
                'bangla_name'  => 'আল বাকী',
                'english_name' => 'Al-Baqi',
                'meaning'      => 'অতি চিরস্থায়ী',
                'description'  => 'যিনি সকল কিছু জানেন',
            ],
            [
                'arabic_name'  => 'الوارث',
                'bangla_name'  => 'আল ওয়ারিস',
                'english_name' => 'Al-Warith',
                'meaning'      => 'সকল কিছু বিতরণ করেন',
                'description'  => 'যিনি সকল কিছু জানেন',
            ],
            [
                'arabic_name'  => 'الرشيد',
                'bangla_name'  => 'আর রাশীদ',
                'english_name' => 'Ar-Rashid',
                'meaning'      => 'অতি বুদ্ধিমান',
                'description'  => 'যিনি সকল কিছু জানেন',
            ],
            [
                'arabic_name'  => 'الصبور',
                'bangla_name'  => 'আস সাবুর',
                'english_name' => 'As-Sabur',
                'meaning'      => 'অতি ধৈর্যশীল',
                'description'  => 'যিনি সকল কিছু জানেন',
            ],
            [
                'arabic_name'  => 'الشكور',
                'bangla_name'  => 'আস শাকূর',
                'english_name' => 'Ash-Shakur',
                'meaning'      => 'অতি কৃতজ্ঞ',
                'description'  => 'যিনি সকল কিছু জানেন',
            ],
            [
                'arabic_name'  => 'العليم',
                'bangla_name'  => 'আল আলীম',
                'english_name' => 'Al-Alim',
                'meaning'      => 'অতি জ্ঞানী',
                'description'  => 'যিনি সকল কিছু জানেন',
            ],
            [
                'arabic_name'  => 'القابض',
                'bangla_name'  => 'আল কাবিদ',
                'english_name' => 'Al-Qabid',
                'meaning'      => 'সকল কিছু ধরেন',
                'description'  => 'যিনি সকল কিছু জানেন',
            ],
            [
                'arabic_name'  => 'الباسط',
                'bangla_name'  => 'আল বাসিত',
                'english_name' => 'Al-Basit',
                'meaning'      => 'সকল কিছু বিস্তার করেন',
                'description'  => 'যিনি সকল কিছু জানেন',
            ],
            [
                'arabic_name'  => 'الخافض',
                'bangla_name'  => 'আল খাফিদ',
                'english_name' => 'Al-Khafid',
                'meaning'      => 'সকল কিছু নিচু করেন',
                'description'  => 'যিনি সকল কিছু জানেন',
            ],
            [
                'arabic_name'  => 'الرافع',
                'bangla_name'  => 'আর রাফী',
                'english_name' => 'Ar-Rafi',
                'meaning'      => 'সকল কিছু উঠানো করেন',
                'description'  => 'যিনি সকল কিছু জানেন',
            ],
            [
                'arabic_name'  => 'المذل',
                'bangla_name'  => 'আল মুদ্বিল',
                'english_name' => 'Al-Mudhill',
                'meaning'      => 'সকল কিছু নিম্ন করেন',
                'description'  => 'যিনি সকল কিছু জানেন',
            ],
            [
                'arabic_name'  => 'السميع',
                'bangla_name'  => 'আস সামী',
                'english_name' => 'As-Sami',
                'meaning'      => 'অতি শোনানো',
                'description'  => 'যিনি সকল কিছু জানেন',
            ],
            [
                'arabic_name'  => 'البصير',
                'bangla_name'  => 'আল বাসীর',
                'english_name' => 'Al-Basir',
                'meaning'      => 'অতি দেখা দেয়',
                'description'  => 'যিনি সকল কিছু জানেন',
            ],
            [
                'arabic_name'  => 'الحكم',
                'bangla_name'  => 'আল হাকম',
                'english_name' => 'Al-Hakam',
                'meaning'      => 'অতি বিচারক',
                'description'  => 'যিনি সকল কিছু জানেন',
            ],
            [
                'arabic_name'  => 'العدل',
                'bangla_name'  => 'আল আদল',
                'english_name' => 'Al-Adl',
                'meaning'      => 'অতি ন্যায়বাদ করেন',
                'description'  => 'যিনি সকল কিছু জানেন',
            ],
        ];

        DB::table('asmaul_husnas')->insert($asmaulHusnas);
    }
}
