<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DoaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $doas = [
            [
                'user_id'         => 1,
                'doa_category_id' => 1,
                'title'           => 'দোয়া ছানা ',
                'doa_for'         => 'দোয়া ছানা ',
                'description'     => 'দোয়া ছানা ',
                'arabic_text'     => 'سُبْحَانَكَ اللَّهُمَّ وَبِحَمْدِكَ، أَشْهَدُ أَنْ لا إِلَهَ إِلَّا أَنْتَ، أَسْتَغْفِرُكَ وَأَتُوبُ إِلَيْكَ',
                'bangla_text'     => 'সুবহানাকাল্লাহুম্মা ওয়া বিহামদিকা আশহাদু আন লা ইলাহা ইল্লাআন্তা আসতাগফিরুকা ওয়া আতুবু ইলাইক।',
                'english_text'    => 'Subhanaka Allahumma wa bihamdika, ash-hadu an la ilaha illa anta, astaghfiruka wa atubu ilaik.',
                'meaning'         => 'হে আল্লাহ! আপনি পবিত্র, আপনি প্রশংসিত। আপনি আমার প্রভু, আপনি আমার প্রশংসিত। আমি আপনার কাছে পাপ করেছি, আপনি আমাকে ক্ষমা করুন এবং আপনার কাছে তাওবা করি।',
                'reference'       => '',
                'when_to_use'     => 'নামাজের প্রথম রাকাতে তাকবীরে তাহরীমার পরে সূরা ফাতিহা পাঠের পূর্বে এই দোয়াটি পাঠ করতে হয়।',
                'notes'           => 'সালাতের দোয়া',
                'when_not_to_use' => 'সালাতের দোয়া',
            ],
            [
                'user_id'         => 1,
                'doa_category_id' => 1,
                'title'           => 'রুকুর দোয়া',
                'doa_for'         => 'রুকুর দোয়া',
                'description'     => 'রুকুর দোয়া',
                'arabic_text'     => 'سُبْحَانَ رَبِّيَ الْعَظِيمِ',
                'bangla_text'     => 'সুবহানা রাব্বিয়াল আযীম',
                'english_text'    => 'Subhana Rabbiyal Azeem.',
                'meaning'         => 'মহান আল্লাহ পাক থাকে।',
                'reference'       => '',
                'when_to_use'     => 'রুকু করার পর এই দোয়াটি পাঠ করতে হয় তিনবার।',
                'notes'           => 'সালাতের দোয়া',
                'when_not_to_use' => 'সালাতের দোয়া',
            ],
            [
                'user_id'         => 1,
                'doa_category_id' => 1,
                'title'           => 'রুকু থেকে ওঠার দোয়া',
                'doa_for'         => 'রুকু থেকে ওঠার দোয়া',
                'description'     => 'রুকু থেকে ওঠার দোয়া',
                'arabic_text'     => 'سَمِعَ اللَّهُ لِمَنْ حَمِدَهُ',
                'bangla_text'     => 'সামিয়াল্লাহু লিমান হামিদাহ',
                'english_text'    => 'Sami Allahu liman hamidah.',
                'meaning'         => 'আল্লাহ পাক শুনেছেন যার প্রশংসা করেছে।',
                'reference'       => '',
                'when_to_use'     => 'রুকু থেকে ওঠার পর এই দোয়াটি পাঠ করতে হয়।',
                'notes'           => 'সালাতের দোয়া',
                'when_not_to_use' => 'সালাতের দোয়া',
            ],
            [
                'user_id'         => 1,
                'doa_category_id' => 1,
                'title'           => 'রুকু থেকে ওঠার পরের দোয়া',
                'doa_for'         => 'রুকু থেকে ওঠার পরের দোয়া',
                'description'     => 'রুকু থেকে ওঠার পরের দোয়া',
                'arabic_text'     => 'رَبَّنَا وَلَكَ الْحَمْدُ حَمْدًا كَثِيرًا طَيِّبًا مُبَارَكًا فِيهِ',
                'bangla_text'     => 'রাব্বানা ওয়ালাকাল হামদু হামদান কাসীরান তাইয্যিবান মুবারাকান ফীহ',
                'english_text'    => 'Rabbana wa lakal hamd, hamdan kathiran tayyiban mubarakan fihi.',
                'meaning'         => 'হে আমাদের প্রভু! আপনার প্রশংসা আপনার জন্য। প্রশংসা যাবে অনেক এবং পবিত্র হবে এই প্রশংসা।',
                'reference'       => '',
                'when_to_use'     => 'রুকু থেকে ওঠার পর এই দোয়াটি পাঠ করতে হয়।',
                'notes'           => 'সালাতের দোয়া',
                'when_not_to_use' => '',
            ],
            [
                'user_id'         => 1,
                'doa_category_id' => 1,
                'title'           => 'সজদার দোয়া',
                'doa_for'         => 'সজদার দোয়া',
                'description'     => 'সজদার দোয়া',
                'arabic_text'     => 'سُبْحَانَ رَبِّيَ الْأَعْلَى',
                'bangla_text'     => 'সুবহানা রাব্বিয়াল আলা',
                'english_text'    => 'Subhana Rabbiyal A’la.',
                'meaning'         => 'মহান আল্লাহ পাক থাকে।',
                'reference'       => '',
                'when_to_use'     => 'সজদা করার পর এই দোয়াটি পাঠ করতে হয় তিনবার।',
                'notes'           => 'সালাতের দোয়া',
                'when_not_to_use' => '',
            ],
            [
                'user_id'         => 1,
                'doa_category_id' => 1,
                'title'           => 'দুই সাজদার মাঝের দোয়া',
                'doa_for'         => 'দুই সাজদার মাঝের দোয়া',
                'description'     => 'দুই সাজদার মাঝের দোয়া',
                'arabic_text'     => 'رَبِّ اغْفِرْ لِي وَارْحَمْنِي وَاجْبُرْنِي وَارْفَعْنِي وَارْزُقْنِي وَاهْدِنِي',
                'bangla_text'     => 'রাব্বিগফিরলী ওয়ারহামনী ওয়াজবুরনী ওয়ারফানী ওয়ারজুকনী ওয়াহদিনী',
                'english_text'    => 'Rabbighfirli warhamni wajburni warfa’ni warzuqni wahdini.',
                'meaning'         => 'হে আমার প্রভু! আমাকে ক্ষমা করুন, আমার উপর রহমত করুন, আমাকে সংকট থেকে মুক্ত করুন, আমাকে উত্তম স্থানে উঠিয়ে নিন, আমাকে রিয়ায়ত করুন, আমাকে নির্দেশ করুন।',
                'reference'       => '',
                'when_to_use'     => 'দুই সাজদার মাঝে এই দোয়াটি পাঠ করতে হয়।',
                'notes'           => 'সালাতের দোয়া',
                'when_not_to_use' => '',
            ],
            [
                'user_id'         => 1,
                'doa_category_id' => 1,
                'title'           => 'তাশাহহুদের দোয়া',
                'doa_for'         => 'তাশাহহুদের দোয়া',
                'description'     => 'তাশাহহুদের দোয়া',
                'arabic_text'     => 'التَّحِيَّاتُ لِلَّهِ وَالصَّلَوَاتُ وَالطَّيِّبَاتُ، السَّلاَمُ عَلَيْكَ أَيُّهَا النَّبِيُّ وَرَحْمَةُ اللَّهِ وَبَرَكَاتُهُ، السَّلاَمُ عَلَيْنَا وَعَلَى عِبَادِ اللَّهِ الصَّالِحِينَ، أَشْهَدُ أَنْ لاَ إِلَهَ إِلاَّ اللَّهُ، وَأَشْهَدُ أَنَّ مُحَمَّدًا عَبْدُهُ وَرَسُولُهُ',
                'bangla_text'     => 'আসসালামু আলাইকা আইয়্যুহান্নবীউ ওয়া রাহমাতুল্লাহি ওয়া বারাকাতুহু আসসালামু আলাইনা ওয়া আলা ইবাদিল্লাহিস সালেহ ইন্নি আশহাদু আল্লা ইলাহা ইল্লাল্লাহু ওয়া আশহাদু আন্না মুহাম্মাদান আব্দুহু ওয়া রাসূলুহু',
                'english_text'    => 'At-tahiyyatul lillahi was-salawatu wat-tayyibatu, As-salamu ‘alaika ayyuhan-Nabiyyu wa rahmatullahi wa barakatuhu, As-salamu ‘alaina wa ‘ala ‘ibadillahis-salihin, Ashhadu an la ilaha illallah wa ashhadu anna Muhammadan ‘abduhu wa Rasuluh.',
                'meaning'         => 'সমস্ত প্রশংসা আল্লাহ পাকের জন্য। সমস্ত সালাম আপনার জন্য, হে নবী! এবং আল্লাহ পাকের রহমত ও বরকত আপনার জন্য। সমস্ত সালাম আমাদের ও আল্লাহ পাকের সৎ বান্দাদের জন্য। আমি সাক্ষ্য দিচ্ছি যে, আল্লাহ পাকের সিরে কাদের ইলাহ নেই এবং আমি সাক্ষ্য দিচ্ছি যে, মুহাম্মাদ (সাঃ) তাঁর বান্দা ও রাসূল।',
                'reference'       => '',
                'when_to_use'     => 'তাশাহহুদের পর এই দোয়াটি পাঠ করতে হয়।',
                'notes'           => 'সালাতের দোয়া',
                'when_not_to_use' => '',
            ],
            [
                'user_id'         => 1,
                'doa_category_id' => 1,
                'title'           => 'দরুদ শরীফ',
                'doa_for'         => 'দরুদ শরীফ',
                'description'     => 'দরুদ শরীফ',
                'arabic_text'     => 'اللَّهُمَّ صَلِّ عَلَى مُحَمَّدٍ وَعَلَى آلِ مُحَمَّدٍ كَمَا صَلَّيْتَ عَلَى إِبْرَاهِيمَ وَعَلَى آلِ إِبْرَاهِيمَ إِنَّكَ حَمِيدٌ مَجِيدٌ اللَّهُمَّ بَارِكْ عَلَى مُحَمَّدٍ وَعَلَى آلِ مُحَمَّدٍ كَمَا بَارَكْتَ عَلَى إِبْرَاهِيمَ وَعَلَى آلِ إِبْرَاهِيمَ إِنَّكَ حَمِيدٌ مَجِيدٌ',
                'bangla_text'     => 'আল্লাহুম্মা সাল্লি আলা মুহাম্মাদিন ওয়া আলা আলি মুহাম্মাদিন কামা সাল্লাইতা আলা ইব্রাহীম ওয়া আলা আলি ইব্রাহীম ইন্নাকা হামিদুম মাজীদ। আল্লাহুম্মা বারিক আলা মুহাম্মাদিন ওয়া আলা আলি মুহাম্মাদিন কামা বারকতা আলা ইব্রাহীম ওয়া আলা আলি ইব্রাহীম ইন্নাকা হামিদুম মাজীদ।',
                'english_text'    => 'Allahumma salli ala muhammadin wa ala ali muhammadin kama sallaita ala ibrahima wa ala ali ibrahima innaka hamidum majid. Allahumma barik ala muhammadin wa ala ali muhammadin kama barakta ala ibrahima wa ala ali ibrahima innaka hamidum majid.',
                'meaning'         => 'হে আল্লাহ! আপনি মুহাম্মাদ ও মুহাম্মাদের পরিবারের উপর রহমত করুন, যেমন আপনি ইব্রাহীম ও ইব্রাহীমের পরিবারের উপর রহমত করেছেন। নিশ্চয়ই আপনি প্রশংসিত ও মহান। হে আল্লাহ! আপনি মুহাম্মাদ ও মুহাম্মাদের পরিবারের উপর বরকত করুন, যেমন আপনি ইব্রাহীম ও ইব্রাহীমের পরিবারের উপর বরকত করেছেন। নিশ্চয়ই আপনি প্রশংসিত ও মহান।',
                'reference'       => 'সহীহ বুখারী, হাদিস নং ১১৩৩',
                'when_to_use'     => 'দ্বিতীয় তাশাহহুদের পর দরুদ শরীফ পড়া হয়। এছাড়া যে কোন সময় পড়া যায়।',
                'notes'           => 'সালাতের দোয়া',
                'when_not_to_use' => 'সালাতের দোয়া',
            ],
            [
                'user_id'         => 1,
                'title'           => 'দোয়া মাছুরা',
                'doa_category_id' => 1,
                'doa_for'         => 'দোয়া মাছুরা',
                'description'     => 'দোয়া মাছুরা',
                'arabic_text'     => 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنْ عِلْمٍ لاَ يَنْفَعُ، وَمِنْ قَلْبٍ لاَ يَخْشَعُ، وَمِنْ نَفْسٍ لاَ تَشْبَعُ، وَمِنْ دَعْوَةٍ لاَ يُسْتَجَابُ لَهَا',
                'bangla_text'     => 'আল্লাহুম্মা ইন্নি আউযুবিকা মিন ইলমিন লা ইয়ানফা’উ ওয়া মিন কালবিন লা ইয়াখশা’উ ওয়া মিন নাফসিন লা তাশবা’উ ওয়া মিন দা’ওয়াতিন লা ইউস্তাজাবু লাহা',
                'english_text'    => 'Allahumma inni a’udhu bika min ‘ilmin la yanfa’u, wa min qalbin la yakhsha’u, wa min nafsin la tashba’u, wa min da’watin la yustajabu laha.',
                'meaning'         => 'হে আল্লাহ! আমি আপনার কাছে আশ্রয় চাই যে জ্ঞান যা কারো কাজে লাগে না, হৃদয় যা ভয় পায় না, নফস যা প্রতীক্ষা করে না এবং দোয়া যা কখনও কবুল হয় না।',
                'reference'       => '',
                'when_to_use'     => 'সালাতের শেষে এই দোয়াটি পাঠ করতে হয়।',
                'notes'           => 'সালাতের দোয়া',
                'when_not_to_use' => '',
            ],

            [
                'user_id'         => 1,
                'title'           => 'দোয়া কুনুত',
                'doa_category_id' => 1,
                'doa_for'         => 'দোয়া কুনুত',
                'description'     => 'দোয়া কুনুত',
                'arabic_text'     => 'اللَّهُمَّ إِنَّا نَسْتَعِينُكَ وَنَسْتَغْفِرُكَ وَنُؤْمِنُ بِكَ وَنَتَوَكَّلُ عَلَيْكَ وَنُثْنِئْ عَلَيْكَ الْخَيْرَ وَنَشْكُرُكَ وَلَا نَكْفُرُكَ وَنَخْلَعُ وَنَتْرُكُ مَنْ يَفْجُرُكَ اللَّهُمَّ إِيَّاكَ نَعْبُدُ وَلَكَ نُصَلِّي وَنَسْجُدُ وَإِلَيْكَ نَسْعَى وَنَحْفِدُ وَنَرْجُو رَحْمَتَكَ وَنَخْشَى عَذَابَكَ إِنَّ عَذَابَكَ بِالْكُفَّارِ مُلْحِقٌ',
                'bangla_text'     => 'আল্লাহুম্মা ইন্না নাসতা’ইনুকা ওয়া নাস্তাগফিরুকা ওয়া নুমিনু বিকা ওয়া নাতাওয়াক্কালু ‘আলাইকা ওয়া নুসনী ‘আলাইকাল খায়রা ওয়া নাশকুরুকা ওয়া লা নাকফুরুকা ওয়া নাখলা’উ ওয়া নাতরুকু মান ইয়াফজুরুকা আল্লাহুম্মা ইয়ায়্যা কা না’বুদু ওয়া লাকা নুসাল্লী ওয়া নাসজুদু ওয়া ইলাইকা নাস’আ ওয়া নাহফিদু ওয়া নারজু রাহমাতাকা ওয়া নাখশা ‘আযাবাকা ইন্না ‘আযাবাকা বিল কুফফারি মুলহিক',
                'english_text'    => 'Allahumma inna nastainuka wa nastaghfiruka wa nu’minu bika wa natawakkalu ‘alaika wa nuthni ‘alaikal khairi wa nashkuruka wa la nakfuruka wa nakhla’u wa natruku mai yafjuruka. Allahumma iyyaka na’budu wa laka nusalli wa nasjudu wa ilaika nas’a wa nahfidu wa narju rahmataka wa nakhsha ‘azabaka inna ‘azabaka bil kuffari mulhik.',
                'meaning'         => 'হে আল্লাহ! আমরা আপনার সাহায্য চাই, আপনার ক্ষমা চাই, আপনার বিশ্বাস করি, আপনার উপর আশ্রয় করি, আপনার উপর ভালোবাসা করি, আপনার উপর কৃতজ্ঞতা প্রকাশ করি, আপনার উপর অস্ত্রাণ্য করি, আপনার উপর ভরসা করি, আপনার রহমত প্রতীক্ষা করি এবং আপনার আযাব থেকে ভয় পাই। নিশ্চয়ই আপনার আযাব কাফেরদের জন্য অবসান হবে।',
                'reference'       => 'সহীহ বুখারী, হাদিস নং ১১৩৩',
                'when_to_use'     => 'সালাতের শেষে এই দোয়াটি পাঠ করতে হয়।',
                'notes'           => 'সালাতের দোয়া',
                'when_not_to_use' => '',
            ],
            [
                'user_id'         => 1,
                'doa_category_id' => 1,
                'title'           => 'সাজদার দোয়া',
                'doa_for'         => 'সাজদার দোয়া',
                'description'     => 'সাজদার দোয়া',
                'arabic_text'     => 'سَجَدَ وَجْهِيَ لِلَّذِي خَلَقَهُ وَشَقَّ سَمْعَهُ وَبَصَرَهُ بِحَوْلِهِ وَقُوَّتِهِ',
                'bangla_text'     => 'সাজাদা ওয়াজহিয়া লিল্লাযি খালাকাহু ওয়াশাক্ব্বা সামহু ওয়াবাসারহু বিহাওলিহি ওয়া কুওয়াতিহি',
                'english_text'    => 'Sajada wajhiya lillazi khalaqahu wa shaqqa sam’ahu wa basarahu bihawlihi wa quwwatihi.',
                'meaning'         => 'আমার মুখ সেই আল্লাহ পাকের জন্য সজদা করেছে, যিনি আমাকে সৃষ্টি করেছেন এবং আমার শ্রবণ ও দৃষ্টি দেওয়ার ক্ষমতা দিয়েছেন।',
                'reference'       => '',
                'when_to_use'     => 'সাজদা করার পর এই দোয়াটি পাঠ করতে হয়।',
                'notes'           => 'সালাতের দোয়া',
                'when_not_to_use' => '',
            ],
            [
                'user_id'         => 1,
                'doa_category_id' => 2,
                'title'           => 'রোজার খোলার দোয়া',
                'doa_for'         => 'রোজার খোলার সময়',
                'description'     => 'রোজা খোলার করার সময় পড়া দোয়া',
                'arabic_text'     => 'اللَّهُمَّ اِنِّى لَكَ صُمْتُ وَبِكَ امنْتُ وَعَلَى رِزْقِكَ اَفْطَرْتُ',
                'bangla_text'     => 'আল্লাহুম্মা ইন্নি লাকা সুমতু ওয়াবিকা আমানতু ওয়াআলা রিজকিকা আফতারতু',
                'english_text'    => 'Allahumma inni laka sumtu wa bika aamantu wa ‘ala rizq-ika-aftartu',
                'meaning'         => 'হে আল্লাহ, আমি তোমার কাছে রোজা রাখলাম, তোমার ইমানে আমি বিশ্বাস করলাম, এবং তোমার রিজ্কের উপর আমি খাবার খেয়েছি।',
                'reference'       => 'সুনান আবু দাউদ, হাদিস নং: ২৩৪৮',
                'when_to_use'     => 'রোজা খোলার করার সময়',
                'notes'           => '',
                'when_not_to_use' => '',
            ],
            [
                'user_id'         => 1,
                'doa_category_id' => 3,
                'title'           => 'সকালের সাথে জিকিরের দোয়া',
                'doa_for'         => 'সকালের সাথে',
                'description'     => 'সকালের সময় পড়া জিকিরের দোয়া',
                'arabic_text'     => 'سُبْحَانَ اللهِ وَبِحَمْدِهِ',
                'bangla_text'     => 'সুবহানাল্লাহি ওয়াবিহামদিহি',
                'english_text'    => 'SubhanAllahi wa bihamdihi',
                'meaning'         => 'আল্লাহ্‌ পাকের পক্ষে পবিত্র এবং তাৎপর্য বিশেষেই এর প্রশংসা করছি।',
                'reference'       => 'সহীহ বুখারী, হাদিস নং: ৬৭২৫',
                'when_to_use'     => 'সকালের সময়',
                'notes'           => '',
                'when_not_to_use' => '',
            ],
            [
                'user_id'         => 1,
                'doa_category_id' => 3,
                'title'           => 'বিকালের সাথে জিকিরের দোয়া',
                'doa_for'         => 'বিকালের সাথে',
                'description'     => 'বিকালের সময় পড়া জিকিরের দোয়া',
                'arabic_text'     => 'اللهُ أَكْبَرُ اللهُ أَكْبَرُ',
                'bangla_text'     => 'আল্লাহু আকবার আল্লাহু আকবার',
                'english_text'    => 'Allahu Akbar, Allahu Akbar',
                'meaning'         => 'আল্লাহ্‌ পাক সবচেয়ে বড়।',
                'reference'       => 'মুসনাদ আহমাদ, হাদিস নং: ৭১৩৫',
                'when_to_use'     => 'বিকালের সময়',
                'notes'           => '',
                'when_not_to_use' => '',
            ],
            [
                'user_id'         => 1,
                'doa_category_id' => 4,
                'title'           => 'omra শুরুর দোয়া',
                'doa_for'         => 'ওমরা শুরু',
                'description'     => 'ওমরা শুরু করার সময় পড়া দোয়া',
                'arabic_text'     => 'لَبَّيْكَ اللَّهُمَّ عُمْرَةً',
                'bangla_text'     => 'লাব্বাইকাল্লাহুম্মা উমরাতান',
                'english_text'    => 'Labbaykallahumma ‘umratan',
                'meaning'         => 'হে আল্লাহ, আমি আপনার ওমরা পালন করতে এসেছি।',
                'reference'       => 'সহীহ মুসলিম, হাদিস নং: ১২২৩',
                'when_to_use'     => 'ওমরা শুরুর সময়',
                'notes'           => '',
                'when_not_to_use' => '',
            ],
            [
                'user_id'         => 1,
                'doa_category_id' => 4,
                'title'           => 'হজ্জের তাওয়াফের দোয়া',
                'doa_for'         => 'হজ্জের তাওয়াফ',
                'description'     => 'কাবার আসার সময় পড়া দোয়া',
                'arabic_text'     => 'اللَّهُمَّ إِنِّى أَعُوذُ بِكَ أَنْ أَضِلَّ أَوْ أُضَلَّ أَوْ أَزِلَّ أَوْ أُزَلَّ أَوْ أَظْلِمَ أَوْ أُظْلَمَ أَوْ أَجْهَلَ أَوْ يُجْهَلَ عَلَىَّ',
                'bangla_text'     => 'আল্লাহুম্মা ইন্নি আ’উযু বিকা অন আডিল্লা অও’ অযিডিল্লা অও’ অজিল্লা অও’ অজিল্লা অও’ অয়লিমা অও’ উযিল্লামা অও’ উয়ল্লামা অও’ অজিহালা অও’ ইয়ুজিহালা আলাইয়া',
                'english_text'    => 'Allahumma inni a’udhu bika an adilla aw udlala aw azilla aw uzalla aw azlima aw uzlama aw ajhala aw yujhala ‘alayya',
                'meaning'         => 'হে আল্লাহ, আমি তোমার পালনে ভুল করব না, নিজে ভুলে পড়ব না, প্রতারিত হতে দেওয়া বা প্রতারিত হওয়ার কারণে লুকিয়ে পড়ব না, প্রতারিত করব না, প্রতারিত করা হওয়ার কারণে লুকিয়ে পড়ব না, আমি অবজ্ঞা করব না বা অবজ্ঞা করার ব্যক্তিকে অবজ্ঞা করতে দিব না।',
                'reference'       => 'সহীহ মুসলিম, হাদিস নং: ২৩৪১',
                'when_to_use'     => 'হজ্জের তাওয়াফের সময়',
                'notes'           => 'এই দোয়া পাঠ করতে হবে হজ্জের তাওয়াফ শুরুর সময়ে।',
                'when_not_to_use' => '',
            ],
            [
                'user_id'         => 1,
                'doa_category_id' => 5,
                'title'           => 'রুকইয়ার শুরুর দোয়া',
                'doa_for'         => 'রুকইয়া শুরু',
                'description'     => 'রুকইয়া শুরু করার সময় পড়া দোয়া',
                'arabic_text'     => 'بِسْمِ اللَّهِ الَّذِي لَا يَضُرُّ مَعَ اسْمِهِ شَيْءٌ فِي الْأَرْضِ وَلَا فِي السَّمَاءِ وَهُوَ السَّمِيعُ الْعَلِيمُ',
                'bangla_text'     => 'বিসমিল্লাহি আল্লাজি লা ইয়াদুর্রু মা’ আসমি’হি শাইউন ফি লারদি ওয়া লা ফি সামাই’ ওয়া হুৱা আস সামিউ’ল আলীম',
                'english_text'    => 'Bismillahi alladhi la yadurru ma\'asmihi shay\'un fil-ardi wa la fis-sama\'i wa huwa as-sami\'u al-alim',
                'meaning'         => 'যাতের নামে, যিনি নিরাপদ না করলে যেকোনো জিনিস পৃথিবীতে বা আকাশে অথবা অন্য কোথাও ক্ষতি করতে পারেন না, এবং তিনি শোন্য ও জ্ঞানী।',
                'reference'       => 'সহীহ বুখারী, হাদিস নং: ০২৩০',
                'when_to_use'     => 'রুকইয়ার শুরুর সময়',
                'notes'           => 'এই দোয়া পাঠ করতে হবে রুকইয়া আরম্ভ করার সময়ে।',
                'when_not_to_use' => '',
            ],
            [
                'user_id'         => 1,
                'doa_category_id' => 5,
                'title'           => 'রুকইয়ার সমাপ্তির দোয়া',
                'doa_for'         => 'রুকইয়া সমাপ্তি',
                'description'     => 'রুকইয়া শেষ করার সময় পড়া দোয়া',
                'arabic_text'     => 'أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّةِ مِنْ شَرِّ مَا خَلَقَ',
                'bangla_text'     => 'আ’উযু বিকালিমাতিল্লাহি ত্তাম্মাতি মিন শারি’মা খালাক',
                'english_text'    => 'A\'udhu bikalimatillahi tammah min sharri ma khalaq',
                'meaning'         => 'আমি আল্লাহর পূর্ণ কলিমার মাধ্যমে তার সৃষ্টির কোনো দুষ্টু ক্রিয়া থেকে আশ্রয় চাই।',
                'reference'       => 'সহীহ মুসলিম, হাদিস নং: ১০০৪',
                'when_to_use'     => 'রুকইয়ার সমাপ্তির সময়',
                'notes'           => 'এই দোয়া পাঠ করতে হবে রুকইয়া শেষ করার সময়ে।',
                'when_not_to_use' => '',
            ],
//             prepare me all doas for Rosa or siam fullfiling with the following structure

// [
//                 'user_id'         => 1,
//                 'doa_category_id' => 2,
//                 'title'           => '',
//                 'doa_for'         => '',
//                 'description'     => '',
//                 'arabic_text'     => '',
//                 'bangla_text'     => '',
//                 'english_text'    => '',
//                 'meaning'         => '',
//                 'reference'       => '',
//                 'when_to_use' => '',
//                 'notes'           => '',
//                 'when_not_to_use' => '',
//             ],
// where title will be in bangla language, do a_for and description also will be in bangla language. arabic_text is the doa written in  arabic language, bangla_text is the pronunciation  of the arabic_text, English_text is the English pronunciation of the arabic_text and meaning is in the bangla language. reference is the hadith number and when_to_use is the time when the doa should be used. notes is the additional information about the doa and when_not_to_use is the time when the doa should not be used.

        ];

        DB::table('doas')->insert($doas);
    }
}