<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SuraTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // write seeder for suras table
        $suras = [
            [
                'name' => 'Al-Fatihah',
                'arabic_name' => 'الفاتحة',
                'english_name' => 'The Opening',
                'meaning' => 'The Opening',
                'ayat_count' => '7',
                'type' => 'Meccan',
                'revelation_order' => '5',
                'rukus' => '1',
                'place_of_revelation' => 'Mecca',
                'status' => 'active',
                'audio' => 'https://server8.mp3quran.net/basit/001.mp3',
                'video' => 'https://www.youtube.com/watch?v=VHfJY3YpLj8',
                'image' => 'https://i.ytimg.com/vi/VHfJY3YpLj8/maxresdefault.jpg',
            ],
            [
                'name' => 'Al-Baqarah',
                'arabic_name' => 'البقرة',
                'english_name' => 'The Cow',
                'meaning' => 'The Cow',
                'ayat_count' => '286',
                'type' => 'Medinan',
                'revelation_order' => '87',
                'rukus' => '40',
                'place_of_revelation' => 'Medina',
                'status' => 'active',
                'audio' => 'https://server8.mp3quran.net/basit/002.mp3',
                'video' => 'https://www.youtube.com/watch?v=VHfJY3YpLj8',
                'image' => 'https://i.ytimg.com/vi/VHfJY3YpLj8/maxresdefault.jpg',
            ],
            [
                'name' => 'Aal-E-Imran',
                'arabic_name' => 'آل عمران',
                'english_name' => 'The Family of Imran',
                'meaning' => 'The Family of Imran',
                'ayat_count' => '200',
                'type' => 'Medinan',
                'revelation_order' => '89',
                'rukus' => '20',
                'place_of_revelation' => 'Medina',
                'status' => 'active',
                'audio' => 'https://server8.mp3quran.net/basit/003.mp3',
                'video' => 'https://www.youtube.com/watch?v=VHfJY3YpLj8',
                'image' => 'https://i.ytimg.com/vi/VHfJY3YpLj8/maxresdefault.jpg',
            ],
            [
                'name' => 'An-Nisa',
                'arabic_name' => 'النساء',
                'english_name' => 'The Women',
                'meaning' => 'The Women',
                'ayat_count' => '176',
                'type' => 'Medinan',
                'revelation_order' => '92',
                'rukus' => '24',
                'place_of_revelation' => 'Medina',
                'status' => 'active',
                'audio' => 'https://server8.mp3quran.net/basit/004.mp3',
                'video' => 'https://www.youtube.com/watch?v=VHfJY3YpLj8',
                'image' => 'https://i.ytimg.com/vi/VHfJY3YpLj8/maxresdefault.jpg',
            ],
            [
                'name' => 'Al-Ma\'idah',
                'arabic_name' => 'المائدة',
                'english_name' => 'The Table Spread',
                'meaning' => 'The Table Spread',
                'ayat_count' => '120',
                'type' => 'Medinan',
                'revelation_order' => '112',
                'rukus' => '16',
                'place_of_revelation' => 'Medina',
                'status' => 'active',
                'audio' => 'https://server8.mp3quran.net/basit/005.mp3',
                'video' => 'https://www.youtube.com/watch?v=VHfJY3YpLj8',
                'image' => 'https://i.ytimg.com/vi/VHfJY3YpLj8/maxresdefault.jpg',
            ],
            [
                'name' => 'Al-An\'am',
                'arabic_name' => 'الأنعام',
                'english_name' => 'The Cattle',
                'meaning' => 'The Cattle',
                'ayat_count' => '165',
                'type' => 'Meccan',
                'revelation_order' => '55',
                'rukus' => '20',
                'place_of_revelation' => 'Mecca',
                'status' => 'active',
                'audio' => 'https://server8.mp3quran.net/basit/006.mp3',
                'video' => 'https://www.youtube.com/watch?v=VHfJY3YpLj8',
                'image' => 'https://i.ytimg.com/vi/VHfJY3YpLj8/maxresdefault.jpg',
            ],
            [
                'name' => 'Al-A\'raf',
                'arabic_name' => 'الأعراف',
                'english_name' => 'The Heights',
                'meaning' => 'The Heights',
                'ayat_count' => '206',
                'type' => 'Meccan',
                'revelation_order' => '39',
                'rukus' => '24',
                'place_of_revelation' => 'Mecca',
                'status' => 'active',
                'audio' => 'https://server8.mp3quran.net/basit/007.mp3',
                'video' => 'https://www.youtube.com/watch?v=VHfJY3YpLj8',
                'image' => 'https://i.ytimg.com/vi/VHfJY3YpLj8/maxresdefault.jpg',
            ],
            [
                'name' => 'Al-Anfal',
                'arabic_name' => 'الأنفال',
                'english_name' => 'The Spoils of War',
                'meaning' => 'The Spoils of War',
                'ayat_count' => '75',
                'type' => 'Medinan',
                'revelation_order' => '88',
                'rukus' => '10',
                'place_of_revelation' => 'Medina',
                'status' => 'active',
                'audio' => 'https://server8.mp3quran.net/basit/008.mp3',
                'video' => 'https://www.youtube.com/watch?v=VHfJY3YpLj8',
                'image' => 'https://i.ytimg.com/vi/VHfJY3YpLj8/maxresdefault.jpg',
            ],
            // [
            //     'name' => 'At-Tawbah',
            //     'arabic_name' => 'التوبة',
            //     'english_name' => 'The Repentance',
            //     'meaning' => 'The Repentance',
            // ],
            // [
            //     'name' => 'Yunus',
            //     'arabic_name' => 'يونس',
            //     'english_name' => 'Jonah',
            //     'meaning' => 'Jonah',
            // ],
            // [
            //     'name' => 'Hud',
            //     'arabic_name' => 'هود',
            //     'english_name' => 'Hud',
            //     'meaning' => 'Hud',
            // ],
            // [
            //     'name' => 'Yusuf',
            //     'arabic_name' => 'يوسف',
            //     'english_name' => 'Joseph',
            //     'meaning' => 'Joseph',
            // ],
            // [
            //     'name' => 'Ar-Ra\'d',
            //     'arabic_name' => 'الرعد',
            //     'english_name' => 'The Thunder',
            //     'meaning' => 'The Thunder',
            // ],
            // [
            //     'name' => 'Ibrahim',
            //     'arabic_name' => 'إبراهيم',
            //     'english_name' => 'Abraham',
            //     'meaning' => 'Abraham',
            // ],
            // [
            //     'name' => 'Al-Hijr',
            //     'arabic_name' => 'الحجر',
            //     'english_name' => 'The Rocky Tract',
            //     'meaning' => 'The Rocky Tract',
            // ],
            // [
            //     'name' => 'An-Nahl',
            //     'arabic_name' => 'النحل',
            //     'english_name' => 'The Bee',
            //     'meaning' => 'The Bee',
            // ],
            // [
            //     'name' => 'Al-Isra',
            //     'arabic_name' => 'الإسراء',
            //     'english_name' => 'The Night Journey',
            //     'meaning' => 'The Night Journey',
            // ],
            // [
            //     'name' => 'Al-Kahf',
            //     'arabic_name' => 'الكهف',
            //     'english_name' => 'The Cave',
            //     'meaning' => 'The Cave',
            // ],
            // [
            //     'name' => 'Maryam',
            //     'arabic_name' => 'مريم',
            //     'english_name' => 'Mary',
            //     'meaning' => 'Mary',
            // ],
            // [
            //     'name' => 'Ta-Ha',
            //     'arabic_name' => 'طه',
            //     'english_name' => 'Ta-Ha',
            //     'meaning' => 'Ta-Ha',
            // ],
            // [
            //     'name' => 'Al-Anbiya',
            //     'arabic_name' => 'الأنبياء',
            //     'english_name' => 'The Prophets',
            //     'meaning' => 'The Prophets',
            // ],
            // [
            //     'name' => 'Al-Hajj',
            //     'arabic_name' => 'الحج',
            //     'english_name' => 'The Pilgrimage',
            //     'meaning' => 'The Pilgrimage',
            // ],
            // [
            //     'name' => 'Al-Muminun',
            //     'arabic_name' => 'المؤمنون',
            //     'english_name' => 'The Believers',
            //     'meaning' => 'The Believers',
            // ],
            // [
            //     'name' => 'Az-Zumar',
            //     'arabic_name' => 'الزمر',
            //     'english_name' => 'The Troops',
            //     'meaning' => 'The Troops',
            // ],
            // [
            //     'name' => 'Ghafir',
            //     'arabic_name' => 'غافر',
            //     'english_name' => 'The Forgiver',
            //     'meaning' => 'The Forgiver',
            // ],
            // [
            //     'name' => 'Fussilat',
            //     'arabic_name' => 'فصلت',
            //     'english_name' => 'Explained in Detail',
            //     'meaning' => 'Explained in Detail',
            // ],
            // [
            //     'name' => 'Ash-Shura',
            //     'arabic_name' => 'الشورى',
            //     'english_name' => 'The Consultation',
            //     'meaning' => 'The Consultation',
            // ],
            // [
            //     'name' => 'Az-Zukhruf',
            //     'arabic_name' => 'الزخرف',
            //     'english_name' => 'The Ornaments of Gold',
            //     'meaning' => 'The Ornaments of Gold',
            // ],
            // [
            //     'name' => 'Ad-Dukhan',
            //     'arabic_name' => 'الدخان',
            //     'english_name' => 'The Smoke',
            //     'meaning' => 'The Smoke',
            // ],
            // [
            //     'name' => 'Al-Jathiyah',
            //     'arabic_name' => 'الجاثية',
            //     'english_name' => 'The Crouching',
            //     'meaning' => 'The Crouching',
            // ],
            // [
            //     'name' => 'Al-Ahqaf',
            //     'arabic_name' => 'الأحقاف',
            //     'english_name' => 'The Wind-Curved Sandhills',
            //     'meaning' => 'The Wind-Curved Sandhills',
            // ],
            // [
            //     'name' => 'Muhammad',
            //     'arabic_name' => 'محمد',
            //     'english_name' => 'Muhammad',
            //     'meaning' => 'Muhammad',
            // ],
            // [
            //     'name' => 'Al-Fath',
            //     'arabic_name' => 'الفتح',
            //     'english_name' => 'The Victory',
            //     'meaning' => 'The Victory',
            // ],
            // [
            //     'name' => 'Al-Hujurat',
            //     'arabic_name' => 'الحجرات',
            //     'english_name' => 'The Rooms',
            //     'meaning' => 'The Rooms',
            // ],
            // [
            //     'name' => 'Qaf',
            //     'arabic_name' => 'ق',
            //     'english_name' => 'Qaf',
            //     'meaning' => 'Qaf',
            // ],
            // [
            //     'name' => 'Ad-Dhariyat',
            //     'arabic_name' => 'الذاريات',
            //     'english_name' => 'The Scatterers',
            //     'meaning' => 'The Scatterers',
            // ],
            // [
            //     'name' => 'At-Tur',
            //     'arabic_name' => 'الطور',
            //     'english_name' => 'The Mount',
            //     'meaning' => 'The Mount',
            // ],
            // [
            //     'name' => 'An-Najm',
            //     'arabic_name' => 'النجم',
            //     'english_name' => 'The Star',
            //     'meaning' => 'The Star',
            // ],
            // [
            //     'name' => 'Al-Qamar',
            //     'arabic_name' => 'القمر',
            //     'english_name' => 'The Moon',
            //     'meaning' => 'The Moon',
            // ],
            // [
            //     'name' => 'Ar-Rahman',
            //     'arabic_name' => 'الرحمن',
            //     'english_name' => 'The Beneficent',
            //     'meaning' => 'The Beneficent',
            // ],
            // [
            //     'name' => 'Al-Waqi\'ah',
            //     'arabic_name' => 'الواقعة',
            //     'english_name' => 'The Inevitable',
            //     'meaning' => 'The Inevitable',
            // ],
            // [
            //     'name' => 'Al-Hadid',
            //     'arabic_name' => 'الحديد',
            //     'english_name' => 'The Iron',
            //     'meaning' => 'The Iron',
            // ],
            // [
            //     'name' => 'Al-Mujadila',
            //     'arabic_name' => 'المجادلة',
            //     'english_name' => 'Al Mujadila',
            //     'meaning' => 'Al Mujadila',
            // ],
            // [
            //     'name' => 'Al-Hashr',
            //     'arabic_name' => 'الحشر',
            //     'english_name' => 'The Exile',
            //     'meaning' => 'The Exile',
            // ],
            // [
            //     'name' => 'Al-Mumtahanah',
            //     'arabic_name' => 'الممتحنة',
            //     'english_name' => 'She that is to be examined',
            //     'meaning' => 'She that is to be examined',
            // ],
            // [
            //     'name' => 'As-Saff',
            //     'arabic_name' => 'الصف',
            //     'english_name' => 'The Ranks',
            //     'meaning' => 'The Ranks',
            // ],
            // [
            //     'name' => 'Al-Jumu\'ah',
            //     'arabic_name' => 'الجمعة',
            //     'english_name' => 'The Congregation',
            //     'meaning' => 'The Congregation',
            // ],
            // [
            //     'name' => 'Al-Munafiqun',
            //     'arabic_name' => 'المنافقون',
            //     'english_name' => 'The Hypocrites',
            //     'meaning' => 'The Hypocrites',
            // ],
            // [
            //     'name' => 'At-Taghabun',
            //     'arabic_name' => 'التغابن',
            //     'english_name' => 'The Manifestation of Losses',
            //     'meaning' => 'The Manifestation of Losses',
            // ],
            // [
            //     'name' => 'At-Talaq',
            //     'arabic_name' => 'الطلاق',
            //     'english_name' => 'Divorce',
            //     'meaning' => 'Divorce',
            // ],
            // [
            //     'name' => 'At-Tahrim',
            //     'arabic_name' => 'التحريم',
            //     'english_name' => 'The Prohibition',
            //     'meaning' => 'The Prohibition',
            // ],
            // [
            //     'name' => 'Al-Mulk',
            //     'arabic_name' => 'الملك',
            //     'english_name' => 'The Sovereignty',
            //     'meaning' => 'The Sovereignty',
            // ],
            // [
            //     'name' => 'Al-Qalam',
            //     'arabic_name' => 'القلم',
            //     'english_name' => 'The Pen',
            //     'meaning' => 'The Pen',
            // ],
            // [
            //     'name' => 'Al-Haqqah',
            //     'arabic_name' => 'الحاقة',
            //     'english_name' => 'The Reality',
            //     'meaning' => 'The Reality',
            // ],
            // [
            //     'name' => 'Al-Ma\'arij',
            //     'arabic_name' => 'المعارج',
            //     'english_name' => 'The Ascending Stairways',
            //     'meaning' => 'The Ascending Stairways',
            // ],
            // [
            //     'name' => 'Nuh',
            //     'arabic_name' => 'نوح',
            //     'english_name' => 'Noah',
            //     'meaning' => 'Noah',
            // ],
            // [
            //     'name' => 'Al-Jinn',
            //     'arabic_name' => 'الجن',
            //     'english_name' => 'The Jinn',
            //     'meaning' => 'The Jinn',
            // ],
            // [
            //     'name' => 'Al-Muzzammil',
            //     'arabic_name' => 'المزمل',
            //     'english_name' => 'The Enshrouded One',
            //     'meaning' => 'The Enshrouded One',
            // ],
            // [
            //     'name' => 'Al-Muddaththir',
            //     'arabic_name' => 'المدثر',
            //     'english_name' => 'The Cloaked One',
            //     'meaning' => 'The Cloaked One',
            // ],
            // [
            //     'name' => 'Al-Qiyamah',
            //     'arabic_name' => 'القيامة',
            //     'english_name' => 'The Resurrection',
            //     'meaning' => 'The Resurrection',
            // ],
            // [
            //     'name' => 'Al-Insan',
            //     'arabic_name' => 'الإنسان',
            //     'english_name' => 'Man',
            //     'meaning' => 'Man'
            // ]
        ];

        DB::table('suras')->insert($suras);

    }
}
