<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SuraTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // write seeder for suras table
        $suras = [
            [
                'name'                => 'Al-Fatihah',
                'arabic_name'         => 'الفاتحة',
                'english_name'        => 'The Opening',
                'meaning'             => 'The Opening',
                'ayat_count'          => '7',
                'type'                => 'Meccan',
                'revelation_order'    => '5',
                'rukus'               => '1',
                'place_of_revelation' => 'Mecca',
                'status'              => 'active',
                'audio'               => 'https://server8.mp3quran.net/basit/001.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3YpLj8',
                'image'               => 'https://i.ytimg.com/vi/VHfJY3YpLj8/maxresdefault.jpg',
            ],
            [
                'name'                => 'Al-Baqarah',
                'arabic_name'         => 'البقرة',
                'english_name'        => 'The Cow',
                'meaning'             => 'The Cow',
                'ayat_count'          => '286',
                'type'                => 'Medinan',
                'revelation_order'    => '87',
                'rukus'               => '40',
                'place_of_revelation' => 'Medina',
                'status'              => 'active',
                'audio'               => 'https://server8.mp3quran.net/basit/002.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3YpLj8',
                'image'               => 'https://i.ytimg.com/vi/VHfJY3YpLj8/maxresdefault.jpg',
            ],
            [
                'name'                => 'Aal-E-Imran',
                'arabic_name'         => 'آل عمران',
                'english_name'        => 'The Family of Imran',
                'meaning'             => 'The Family of Imran',
                'ayat_count'          => '200',
                'type'                => 'Medinan',
                'revelation_order'    => '89',
                'rukus'               => '20',
                'place_of_revelation' => 'Medina',
                'status'              => 'active',
                'audio'               => 'https://server8.mp3quran.net/basit/003.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3YpLj8',
                'image'               => 'https://i.ytimg.com/vi/VHfJY3YpLj8/maxresdefault.jpg',
            ],
            [
                'name'                => 'An-Nisa',
                'arabic_name'         => 'النساء',
                'english_name'        => 'The Women',
                'meaning'             => 'The Women',
                'ayat_count'          => '176',
                'type'                => 'Medinan',
                'revelation_order'    => '92',
                'rukus'               => '24',
                'place_of_revelation' => 'Medina',
                'status'              => 'active',
                'audio'               => 'https://server8.mp3quran.net/basit/004.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3YpLj8',
                'image'               => 'https://i.ytimg.com/vi/VHfJY3YpLj8/maxresdefault.jpg',
            ],
            [
                'name'                => 'Al-Ma\'idah',
                'arabic_name'         => 'المائدة',
                'english_name'        => 'The Table Spread',
                'meaning'             => 'The Table Spread',
                'ayat_count'          => '120',
                'type'                => 'Medinan',
                'revelation_order'    => '112',
                'rukus'               => '16',
                'place_of_revelation' => 'Medina',
                'status'              => 'active',
                'audio'               => 'https://server8.mp3quran.net/basit/005.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3YpLj8',
                'image'               => 'https://i.ytimg.com/vi/VHfJY3YpLj8/maxresdefault.jpg',
            ],
            [
                'name'                => 'Al-An\'am',
                'arabic_name'         => 'الأنعام',
                'english_name'        => 'The Cattle',
                'meaning'             => 'The Cattle',
                'ayat_count'          => '165',
                'type'                => 'Meccan',
                'revelation_order'    => '55',
                'rukus'               => '20',
                'place_of_revelation' => 'Mecca',
                'status'              => 'active',
                'audio'               => 'https://server8.mp3quran.net/basit/006.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3YpLj8',
                'image'               => 'https://i.ytimg.com/vi/VHfJY3YpLj8/maxresdefault.jpg',
            ],
            [
                'name'                => 'Al-A\'raf',
                'arabic_name'         => 'الأعراف',
                'english_name'        => 'The Heights',
                'meaning'             => 'The Heights',
                'ayat_count'          => '206',
                'type'                => 'Meccan',
                'revelation_order'    => '39',
                'rukus'               => '24',
                'place_of_revelation' => 'Mecca',
                'status'              => 'active',
                'audio'               => 'https://server8.mp3quran.net/basit/007.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3YpLj8',
                'image'               => 'https://i.ytimg.com/vi/VHfJY3YpLj8/maxresdefault.jpg',
            ],
            [
                'name'                => 'Al-Anfal',
                'arabic_name'         => 'الأنفال',
                'english_name'        => 'The Spoils of War',
                'meaning'             => 'The Spoils of War',
                'ayat_count'          => '75',
                'type'                => 'Medinan',
                'revelation_order'    => '88',
                'rukus'               => '10',
                'place_of_revelation' => 'Medina',
                'status'              => 'active',
                'audio'               => 'https://server8.mp3quran.net/basit/008.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3YpLj8',
                'image'               => 'https://i.ytimg.com/vi/VHfJY3YpLj8/maxresdefault.jpg',
            ],
            [
                'name'                => 'At-Tawbah',
                'arabic_name'         => 'التوبة',
                'english_name'        => 'The Repentance',
                'meaning'             => 'The Repentance',
                'ayat_count'          => '129',
                'type'                => 'Medinan',
                'revelation_order'    => '113',
                'rukus'               => '16',
                'place_of_revelation' => 'Medina',
                'status'              => 'active',
                'audio'               => 'https://server8.mp3quran.net/basit/009.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3YpLj8',
                'image'               => 'https://i.ytimg.com/vi/VHfJY3YpLj8/maxresdefault.jpg',

            ],
            [
                'name'                => 'Yunus',
                'arabic_name'         => 'يونس',
                'english_name'        => 'Jonah',
                'meaning'             => 'Jonah',
                'ayat_count'          => '109',
                'type'                => 'Meccan',
                'revelation_order'    => '51',
                'rukus'               => '11',
                'place_of_revelation' => 'Mecca',
                'status'              => 'active',
                'audio'               => 'https://server8.mp3quran.net/basit/010.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3YpLj8',
                'image'               => '',
            ],
            [
                'name'                => 'Hud',
                'arabic_name'         => 'هود',
                'english_name'        => 'Hud',
                'meaning'             => 'Hud',
                'ayat_count'          => '123',
                'type'                => 'Meccan',
                'revelation_order'    => '52',
                'rukus'               => '10',
                'place_of_revelation' => 'Mecca',
                'status'              => 'active',
                'audio'               => 'https://server8.mp3quran.net/basit/011.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3Yp',
                'image'               => '',
            ],
            [
                'name'                => 'Yusuf',
                'arabic_name'         => 'يوسف',
                'english_name'        => 'Joseph',
                'meaning'             => 'Joseph',
                'ayat_count'          => '111',
                'type'                => 'Meccan',
                'revelation_order'    => '53',
                'rukus'               => '12',
                'place_of_revelation' => 'Mecca',
                'status'              => 'active',
                'audio'               => 'https://server8.mp3quran.net/basit/012.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3Yp',
                'image'               => '',
            ],
            [
                'name'                => 'Ar-Ra\'d',
                'arabic_name'         => 'الرعد',
                'english_name'        => 'The Thunder',
                'meaning'             => 'The Thunder',
                'ayat_count'          => '43',
                'type'                => 'Medinan',
                'revelation_order'    => '96',
                'rukus'               => '6',
                'place_of_revelation' => 'Medina',
                'status'              => 'active',
                'audio'               => 'https://server8.mp3quran.net/basit/013.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3Yp',
                'image'               => '',
            ],
            [
                'name'                => 'Ibrahim',
                'arabic_name'         => 'إبراهيم',
                'english_name'        => 'Abraham',
                'meaning'             => 'Abraham',
                'ayat_count'          => '52',
                'type'                => 'Meccan',
                'revelation_order'    => '72',
                'rukus'               => '7',
                'place_of_revelation' => 'Mecca',
                'status'              => 'active',
                'audio'               => 'https://server8.mp3quran.net/basit/014.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3Yp',
                'image'               => '',
            ],
            [
                'name'                => 'Al-Hijr',
                'arabic_name'         => 'الحجر',
                'english_name'        => 'The Rocky Tract',
                'meaning'             => 'The Rocky Tract',
                'ayat_count'          => '99',
                'type'                => 'Meccan',
                'revelation_order'    => '54',
                'rukus'               => '6',
                'place_of_revelation' => 'Mecca',
                'status'              => 'active',
                'audio'               => 'https://server8.mp3quran.net/basit/015.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3Yp',
                'image'               => '',
            ],
            [
                'name'                => 'An-Nahl',
                'arabic_name'         => 'النحل',
                'english_name'        => 'The Bee',
                'meaning'             => 'The Bee',
                'ayat_count'          => '128',
                'type'                => 'Meccan',
                'revelation_order'    => '70',
                'rukus'               => '16',
                'place_of_revelation' => 'Mecca',
                'status'              => 'active',
                'audio'               => 'https://server8.mp3quran.net/basit/016.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3Yp',
                'image'               => '',
            ],
            [
                'name'                => 'Al-Isra',
                'arabic_name'         => 'الإسراء',
                'english_name'        => 'The Night Journey',
                'meaning'             => 'The Night Journey',
                'ayat_count'          => '111',
                'type'                => 'Meccan',
                'revelation_order'    => '50',
                'rukus'               => '12',
                'place_of_revelation' => 'Mecca',
                'status'              => 'active',
                'audio'               => 'https://server8.mp3quran.net/basit/017.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3Yp',
                'image'               => '',
            ],
            [
                'name'                => 'Al-Kahf',
                'arabic_name'         => 'الكهف',
                'english_name'        => 'The Cave',
                'meaning'             => 'The Cave',
                'ayat_count'          => '110',
                'type'                => 'Meccan',
                'revelation_order'    => '69',
                'rukus'               => '12',
                'place_of_revelation' => 'Mecca',
                'status'              => 'active',
                'audio'               => 'https://server8.mp3quran.net/basit/018.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3Yp',
                'image'               => '',
            ],
            [
                'name'                => 'Maryam',
                'arabic_name'         => 'مريم',
                'english_name'        => 'Mary',
                'meaning'             => 'Mary',
                'ayat_count'          => '98',
                'type'                => 'Meccan',
                'revelation_order'    => '44',
                'rukus'               => '6',
                'place_of_revelation' => 'Mecca',
                'status'              => 'active',
                'audio'               => 'https://server8.mp3quran.net/basit/019.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3Yp',
                'image'               => '',
            ],
            [
                'name'                => 'Ta-Ha',
                'arabic_name'         => 'طه',
                'english_name'        => 'Ta-Ha',
                'meaning'             => 'Ta-Ha',
                'ayat_count'          => '135',
                'type'                => 'Meccan',
                'revelation_order'    => '45',
                'rukus'               => '8',
                'place_of_revelation' => 'Mecca',
                'status'              => 'active',
                'audio'               => 'https://server8.mp3quran.net/basit/020.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3Yp',
                'image'               => '',
            ],
            [
                'name'                => 'Al-Anbiya',
                'arabic_name'         => 'الأنبياء',
                'english_name'        => 'The Prophets',
                'meaning'             => 'The Prophets',
                'ayat_count'          => '112',
                'type'                => 'Meccan',
                'revelation_order'    => '73',
                'rukus'               => '7',
                'place_of_revelation' => 'Mecca',
                'status'              => 'active',
                'audio'               => 'https://server8.mp3quran.net/basit/021.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3Yp',
                'image'               => '',
            ],
            [
                'name'                => 'Al-Hajj',
                'arabic_name'         => 'الحج',
                'english_name'        => 'The Pilgrimage',
                'meaning'             => 'The Pilgrimage',
                'ayat_count'          => '78',
                'type'                => 'Medinan',
                'revelation_order'    => '103',
                'rukus'               => '10',
                'place_of_revelation' => 'Medina',
                'status'              => 'active',
                'audio'               => 'https://server8.mp3quran.net/basit/022.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3Yp',
                'image'               => '',
            ],

            [
                'name'                => 'Al-Muminun',
                'arabic_name'         => 'المؤمنون',
                'english_name'        => 'The Believers',
                'meaning'             => 'The Believers',
                'ayat_count'          => '118',
                'type'                => 'Meccan',
                'revelation_order'    => '74',
                'rukus'               => '6',
                'place_of_revelation' => 'Mecca',
                'status'              => 'active',
                'audio'               => 'https://server8.mp3quran.net/basit/023.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3Yp',
                'image'               => '',
            ],
            [
                'name'                => 'Az-Zumar',
                'arabic_name'         => 'الزمر',
                'english_name'        => 'The Troops',
                'meaning'             => 'The Troops',
                'ayat_count'          => '75',
                'type'                => 'Meccan',
                'revelation_order'    => '102',
                'rukus'               => '8',
                'place_of_revelation' => 'Mecca',
                'status'              => 'active',
                'audio'               => 'https://server8.mp3quran.net/basit/024.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3Yp',
                'image'               => '',
            ],

            [
                'name'                => 'Ghafir',
                'arabic_name'         => 'غافر',
                'english_name'        => 'The Forgiver',
                'meaning'             => 'The Forgiver',
                'ayat_count'          => '85',
                'type'                => 'Meccan',
                'revelation_order'    => '42',
                'rukus'               => '9',
                'place_of_revelation' => 'Mecca',
                'status'              => 'active',
                'audio'               => 'https://server8.mp3quran.net/basit/025.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3Yp',
                'image'               => '',
            ],

            [
                'name'                => 'Fussilat',
                'arabic_name'         => 'فصلت',
                'english_name'        => 'Explained in Detail',
                'meaning'             => 'Explained in Detail',
                'ayat_count'          => '54',
                'type'                => 'Meccan',
                'revelation_order'    => '47',
                'rukus'               => '6',
                'place_of_revelation' => 'Mecca',
                'status'              => 'active',
                'audio'               => 'https://server8.mp3quran.net/basit/026.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3Yp',
                'image'               => '',
            ],
            [
                'name'                => 'Ash-Shura',
                'arabic_name'         => 'الشورى',
                'english_name'        => 'The Consultation',
                'meaning'             => 'The Consultation',
                'ayat_count'          => '53',
                'type'                => 'Meccan',
                'revelation_order'    => '48',
                'rukus'               => '5',
                'place_of_revelation' => 'Mecca',
                'status'              => 'active',
                'audio'               => 'https://server8.mp3quran.net/basit/027.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3Yp',
                'image'               => '',
            ],

            [
                'name'                => 'Az-Zukhruf',
                'arabic_name'         => 'الزخرف',
                'english_name'        => 'The Ornaments of Gold',
                'meaning'             => 'The Ornaments of Gold',
                'ayat_count'          => '89',
                'type'                => 'Meccan',
                'revelation_order'    => '49',
                'rukus'               => '7',
                'place_of_revelation' => 'Mecca',
                'status'              => 'active',
                'audio'               => 'https://server8.mp3quran.net/basit/028.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3Yp',
                'image'               => '',
            ],

            [
                'name'                => 'Ad-Dukhan',
                'arabic_name'         => 'الدخان',
                'english_name'        => 'The Smoke',
                'meaning'             => 'The Smoke',
                'ayat_count'          => '59',
                'type'                => 'Meccan',
                'revelation_order'    => '85',
                'rukus'               => '3',
                'place_of_revelation' => 'Mecca',
                'status'              => 'active',
                'audio'               => 'https://server8.mp3quran.net/basit/029.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3Yp',
                'image'               => '',
            ],
            [
                'name'                => 'Al-Jathiyah',
                'arabic_name'         => 'الجاثية',
                'english_name'        => 'The Crouching',
                'meaning'             => 'The Crouching',
                'ayat_count'          => '37',
                'type'                => 'Meccan',
                'revelation_order'    => '84',
                'rukus'               => '4',
                'place_of_revelation' => 'Mecca',
                'status'              => 'active',
                'audio'               => 'https://server8.mp3quran.net/basit/045.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3Yp',
                'image'               => '',
            ],

            [
                'name'                => 'Al-Ahqaf',
                'arabic_name'         => 'الأحقاف',
                'english_name'        => 'The Wind-Curved Sandhills',
                'meaning'             => 'The Wind-Curved Sandhills',
                'ayat_count'          => '35',
                'type'                => 'Meccan',
                'revelation_order'    => '57',
                'rukus'               => '4',
                'place_of_revelation' => 'Mecca',
                'status'              => 'active',
                'audio'               => 'https://cdn.islamic.network/quran/audio/128/ar.basit/046.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3Yp',
                'image'               => '',
            ],

            [
                'name'                => 'Muhammad',
                'arabic_name'         => 'محمد',
                'english_name'        => 'Muhammad',
                'meaning'             => 'Muhammad',
                'ayat_count'          => '38',
                'type'                => 'Medinan',
                'revelation_order'    => '96',
                'rukus'               => '4',
                'place_of_revelation' => 'Medina',
                'status'              => 'active',
                'audio'               => 'https://cdn.islamic.network/quran/audio/128/ar.basit/047.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3Yp',
                'image'               => '',
            ],
            [
                'name'                => 'Al-Fath',
                'arabic_name'         => 'الفتح',
                'english_name'        => 'The Victory',
                'meaning'             => 'The Victory',
                'ayat_count'          => '29',
                'type'                => 'Medinan',
                'revelation_order'    => '94',
                'rukus'               => '4',
                'place_of_revelation' => 'Medina',
                'status'              => 'active',
                'audio'               => 'https://cdn.islamic.network/quran/audio/128/ar.basit/048.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3Yp',
                'image'               => '',
            ],

            [
                'name'                => 'Al-Hujurat',
                'arabic_name'         => 'الحجرات',
                'english_name'        => 'The Rooms',
                'meaning'             => 'The Rooms',
                'ayat_count'          => '18',
                'type'                => 'Medinan',
                'revelation_order'    => '105',
                'rukus'               => '2',
                'place_of_revelation' => 'Medina',
                'status'              => 'active',
                'audio'               => 'https://cdn.islamic.network/quran/audio/128/ar.basit/049.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3Yp',
                'image'               => '',
            ],

            [
                'name'                => 'Qaf',
                'arabic_name'         => 'ق',
                'english_name'        => 'Qaf',
                'meaning'             => 'Qaf',
                'ayat_count'          => '45',
                'type'                => 'Meccan',
                'revelation_order'    => '43',
                'rukus'               => '3',
                'place_of_revelation' => 'Mecca',
                'status'              => 'active',
                'audio'               => 'https://cdn.islamic.network/quran/audio/128/ar.basit/050.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3Yp',
                'image'               => '',
            ],
            [
                'name'                => 'Adh-Dhariyat',
                'arabic_name'         => 'الذاريات',
                'english_name'        => 'The Winnowing Winds',
                'meaning'             => 'The Winnowing Winds',
                'ayat_count'          => '60',
                'type'                => 'Meccan',
                'revelation_order'    => '41',
                'rukus'               => '3',
                'place_of_revelation' => 'Mecca',
                'status'              => 'active',
                'audio'               => 'https://cdn.islamic.network/quran/audio/128/ar.basit/051.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3Yp',
                'image'               => '',
            ],

            [
                'name'                => 'At-Tur',
                'arabic_name'         => 'الطور',
                'english_name'        => 'The Mount',
                'meaning'             => 'The Mount',
                'ayat_count'          => '49',
                'type'                => 'Meccan',
                'revelation_order'    => '88',
                'rukus'               => '2',
                'place_of_revelation' => 'Mecca',
                'status'              => 'active',
                'audio'               => 'https://cdn.islamic.network/quran/audio/128/ar.basit/052.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3Yp',
                'image'               => '',
            ],

            [
                'name'                => 'An-Najm',
                'arabic_name'         => 'النجم',
                'english_name'        => 'The Star',
                'meaning'             => 'The Star',
                'ayat_count'          => '62',
                'type'                => 'Meccan',
                'revelation_order'    => '66',
                'rukus'               => '3',
                'place_of_revelation' => 'Mecca',
                'status'              => 'active',
                'audio'               => 'https://cdn.islamic.network/quran/audio/128/ar.basit/053.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3Yp',
                'image'               => '',
            ],
            [
                'name'                => 'Al-Qamar',
                'arabic_name'         => 'القمر',
                'english_name'        => 'The Moon',
                'meaning'             => 'The Moon',
                'ayat_count'          => '55',
                'type'                => 'Meccan',
                'revelation_order'    => '95',
                'rukus'               => '3',
                'place_of_revelation' => 'Mecca',
                'status'              => 'active',
                'audio'               => 'https://cdn.islamic.network/quran/audio/128/ar.basit/054.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3Yp',
                'image'               => '',
            ],

            [
                'name'                => 'Ar-Rahman',
                'arabic_name'         => 'الرحمن',
                'english_name'        => 'The Beneficent',
                'meaning'             => 'The Beneficent',
                'ayat_count'          => '78',
                'type'                => 'Medinan',
                'revelation_order'    => '88',
                'rukus'               => '3',
                'place_of_revelation' => 'Medina',
                'status'              => 'active',
                'audio'               => 'https://cdn.islamic.network/quran/audio/128/ar.basit/055.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3Yp',
                'image'               => '',
            ],

            [
                'name'                => 'Al-Waqi\'ah',
                'arabic_name'         => 'الواقعة',
                'english_name'        => 'The Inevitable',
                'meaning'             => 'The Inevitable',
                'ayat_count'          => '96',
                'type'                => 'Meccan',
                'revelation_order'    => '67',
                'rukus'               => '3',
                'place_of_revelation' => 'Mecca',
                'status'              => 'active',
                'audio'               => 'https://cdn.islamic.network/quran/audio/128/ar.basit/056.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3Yp',
                'image'               => '',
            ],
            [
                'name'                => 'Al-Hadid',
                'arabic_name'         => 'الحديد',
                'english_name'        => 'The Iron',
                'meaning'             => 'The Iron',
                'ayat_count'          => '29',
                'type'                => 'Medinan',
                'revelation_order'    => '76',
                'rukus'               => '4',
                'place_of_revelation' => 'Medina',
                'status'              => 'active',
                'audio'               => 'https://cdn.islamic.network/quran/audio/128/ar.basit/057.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3Yp',
                'image'               => '',
            ],
            [
                'name'                => 'Al-Mujadila',
                'arabic_name'         => 'المجادلة',
                'english_name'        => 'Al-Mujadila',
                'meaning'             => 'Al-Mujadila',
                'ayat_count'          => '22',
                'type'                => 'Medinan',
                'revelation_order'    => '83',
                'rukus'               => '3',
                'place_of_revelation' => 'Medina',
                'status'              => 'active',
                'audio'               => 'https://cdn.islamic.network/quran/audio/128/ar.basit/058.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3Yp',
                'image'               => '',
            ],
            [
                'name'                => 'Al-Hashr',
                'arabic_name'         => 'الحشر',
                'english_name'        => 'The Exile',
                'meaning'             => 'The Exile',
                'ayat_count'          => '24',
                'type'                => 'Medinan',
                'revelation_order'    => '27',
                'rukus'               => '3',
                'place_of_revelation' => 'Medina',
                'status'              => 'active',
                'audio'               => 'https://cdn.islamic.network/quran/audio/128/ar.basit/059.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3Yp',
                'image'               => '',
            ],
            [
                'name'                => '\'Al-Mumtahanah',
                'arabic_name'         => 'الممتحنة',
                'english_name'        => 'She that is to be examined',
                'meaning'             => 'She that is to be examined',
                'ayat_count'          => '13',
                'type'                => 'Medinan',
                'revelation_order'    => '101',
                'rukus'               => '2',
                'place_of_revelation' => 'Medina',
                'status'              => 'active',
                'audio'               => 'https://cdn.islamic.network/quran/audio/128/ar.basit/060.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3Yp',
                'image'               => '',
            ],
            [
                'name'                => '\'As-Saff',
                'arabic_name'         => 'الصف',
                'english_name'        => 'The Ranks',
                'meaning'             => 'The Ranks',
                'ayat_count'          => '14',
                'type'                => 'Medinan',
                'revelation_order'    => '91',
                'rukus'               => '2',
                'place_of_revelation' => 'Medina',
                'status'              => 'active',
                'audio'               => 'https://cdn.islamic.network/quran/audio/128/ar.basit/061.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3Yp',
                'image'               => '',
            ],

            [
                'name'                => 'Al-Jumu\'ah',
                'arabic_name'         => 'الجمعة',
                'english_name'        => 'The Congregation',
                'meaning'             => 'The Congregation',
                'ayat_count'          => '11',
                'type'                => 'Medinan',
                'revelation_order'    => '106',
                'rukus'               => '2',
                'place_of_revelation' => 'Medina',
                'status'              => 'active',
                'audio'               => 'https://cdn.islamic.network/quran/audio/128/ar.basit/062.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3Yp',
                'image'               => '',
            ],

            [
                'name'                => '\'Al-Munafiqun',
                'arabic_name'         => 'المنافقون',
                'english_name'        => 'The Hypocrites',
                'meaning'             => 'The Hypocrites',
                'ayat_count'          => '11',
                'type'                => 'Medinan',
                'revelation_order'    => '104',
                'rukus'               => '2',
                'place_of_revelation' => 'Medina',
                'status'              => 'active',
                'audio'               => 'https://cdn.islamic.network/quran/audio/128/ar.basit/063.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3Yp',
                'image'               => '',
            ],

            [
                'name'                => '\'At-Taghabun',
                'arabic_name'         => 'التغابن',
                'english_name'        => 'Mutual Disillusion',
                'meaning'             => 'Mutual Disillusion',
                'ayat_count'          => '18',
                'type'                => 'Medinan',
                'revelation_order'    => '108',
                'rukus'               => '2',
                'place_of_revelation' => 'Medina',
                'status'              => 'active',
                'audio'               => 'https://cdn.islamic.network/quran/audio/128/ar.basit/064.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3Yp',
                'image'               => '',
            ],
            [
                'name'                => '\'At-Talaq',
                'arabic_name'         => 'الطلاق',
                'english_name'        => 'Divorce',
                'meaning'             => 'Divorce',
                'ayat_count'          => '12',
                'type'                => 'Medinan',
                'revelation_order'    => '99',
                'rukus'               => '2',
                'place_of_revelation' => 'Medina',
                'status'              => 'active',
                'audio'               => '',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3Yp',
                'image'               => '',
            ],

            [
                'name'                => '\'At-Tahrim',
                'arabic_name'         => 'التحريم',
                'english_name'        => 'The Prohibition',
                'meaning'             => 'The Prohibition',
                'ayat_count'          => '12',
                'type'                => 'Medinan',
                'revelation_order'    => '107',
                'rukus'               => '2',
                'place_of_revelation' => 'Medina',
                'status'              => 'active',
                'audio'               => '',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3Yp',
                'image'               => '',
            ],

            [
                'name'                => 'Al-Mulk',
                'arabic_name'         => 'الملك',
                'english_name'        => 'The Sovereignty',
                'meaning'             => 'The Sovereignty',
                'ayat_count'          => '30',
                'type'                => 'Meccan',
                'revelation_order'    => '77',
                'rukus'               => '2',
                'place_of_revelation' => 'Mecca',
                'status'              => 'active',
                'audio'               => '',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3Yp',
                'image'               => '',
            ],

            [
                'name'                => 'Al-Qalam',
                'arabic_name'         => 'القلم',
                'english_name'        => 'The Pen',
                'meaning'             => 'The Pen',
                'ayat_count'          => '52',
                'type'                => 'Meccan',
                'revelation_order'    => '2',
                'rukus'               => '2',
                'place_of_revelation' => 'Mecca',
                'status'              => 'active',
                'audio'               => '',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3Yp',
                'image'               => '',
            ],
            [
                'name'                => 'Al-Haqqah',
                'arabic_name'         => 'الحاقة',
                'english_name'        => 'The Reality',
                'meaning'             => 'The Reality',
                'ayat_count'          => '52',
                'type'                => 'Meccan',
                'revelation_order'    => '78',
                'rukus'               => '2',
                'place_of_revelation' => 'Mecca',
                'status'              => 'active',
                'audio'               => '',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3Yp',
                'image'               => '',
            ],

            [
                'name'                => 'Al-Ma\'arij',
                'arabic_name'         => 'المعارج',
                'english_name'        => 'The Ascending Stairways',
                'meaning'             => 'The Ascending Stairways',
                'ayat_count'          => '44',
                'type'                => 'Meccan',
                'revelation_order'    => '79',
                'rukus'               => '2',
                'place_of_revelation' => 'Mecca',
                'status'              => 'active',
                'audio'               => '',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3Yp',
                'image'               => '',
            ],
            [
                'name'                => 'Nuh',
                'arabic_name'         => 'نوح',
                'english_name'        => 'Noah',
                'meaning'             => 'Noah',
                'ayat_count'          => '28',
                'type'                => 'Meccan',
                'revelation_order'    => '71',
                'rukus'               => '2',
                'place_of_revelation' => 'Mecca',
                'status'              => 'active',
                'audio'               => '',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3Yp',
                'image'               => '',
            ],
            [
                'name'                => 'Al-Jinn',
                'arabic_name'         => 'الجن',
                'english_name'        => 'The Jinn',
                'meaning'             => 'The Jinn',
                'ayat_count'          => '28',
                'type'                => 'Meccan',
                'revelation_order'    => '40',
                'rukus'               => '2',
                'place_of_revelation' => 'Mecca',
                'status'              => 'active',
                'audio'               => '',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3Yp',
                'image'               => '',
            ],

            [
                'name'                => 'Al-Muzzammil',
                'arabic_name'         => 'المزمل',
                'meaning'             => 'The One Covering Himself',
                'english_name'        => 'The Enshrouded One',
                'meaning'             => 'The One Who Wraps Himself Up',
                'ayat_count'          => '20',
                'type'                => 'Makki',
                'revelation_order'    => '73',
                'rukus'               => '2',
                'place_of_revelation' => 'Makkah',
                'status'              => 'active',
                'audio'               => 'audio_url_for_Al_Muzzammil',
                'video'               => 'video_url_for_Al_Muzzammil',
                'image'               => 'image_url_for_Al_Muzzammil',
            ],
            [
                'name'                => 'Al-Muddathir',
                'arabic_name'         => 'المدثر',
                'meaning'             => 'The One Wrapping Himself Up',
                'english_name'        => 'The Cloaked One',
                'meaning'             => 'The One Who Is Enveloped',
                'ayat_count'          => '56',
                'type'                => 'Makki',
                'revelation_order'    => '2',
                'rukus'               => '2',
                'place_of_revelation' => 'Makkah',
                'status'              => 'active',
                'audio'               => 'audio_url_for_Al_Muddathir',
                'video'               => 'video_url_for_Al_Muddathir',
                'image'               => 'image_url_for_Al_Muddathir',
            ],
            [
                'name'                => 'Al-Qiyamah',
                'arabic_name'         => 'القيامة',
                'meaning'             => 'The Resurrection',
                'english_name'        => 'The Resurrection',
                'meaning'             => 'The Resurrection',
                'ayat_count'          => '40',
                'type'                => 'Makki',
                'revelation_order'    => '75',
                'rukus'               => '1',
                'place_of_revelation' => 'Makkah',
                'status'              => 'active',
                'audio'               => 'audio_url_for_Al_Qiyamah',
                'video'               => 'video_url_for_Al_Qiyamah',
                'image'               => 'image_url_for_Al_Qiyamah',
            ],
            [
                'name'                => 'Al-Insan',
                'arabic_name'         => 'الإنسان',
                'meaning'             => 'The Man',
                'english_name'        => 'The Human',
                'meaning'             => 'The Human Being',
                'ayat_count'          => '31',
                'type'                => 'Madani',
                'revelation_order'    => '76',
                'rukus'               => '3',
                'place_of_revelation' => 'Madina',
                'status'              => 'active',
                'audio'               => 'audio_url_for_Al_Insan',
                'video'               => 'video_url_for_Al_Insan',
                'image'               => 'image_url_for_Al_Insan',
            ],

//            prepare me the data of sura  AL-MURSALAAT - THOSE SENT FORTH, AN-NABA - THE NEWS, AN-NAZIAT - THOSE WHO PULL OUT with the following structure

// [
//                 'name' => '',
//                 'arabic_name' => '',
//                 'meaning' => '',
//                 'english_name' => '',
//                 'meaning' => '',
//                 'ayat_count' => '',
//                 'type' => '',
//                 'revelation_order' => '',
//                 'rukus' => '',
//                 'place_of_revelation' => '',
//                 'status' => '',
//                 'audio' => '',
//                 'video' => '',
//                 'image' => '',
//             ]

            // [
            //     'name' => 'At-Tawbah',
            //     'arabic_name' => 'التوبة',
            //     'english_name' => 'The Repentance',
            //     'meaning' => 'The Repentance',
            // ],
            // [
            //     'name' => 'Yunus',
            //     'arabic_name' => 'يونس',
            //     'english_name' => 'Jonah',
            //     'meaning' => 'Jonah',
            // ],
            // [
            //     'name' => 'Hud',
            //     'arabic_name' => 'هود',
            //     'english_name' => 'Hud',
            //     'meaning' => 'Hud',
            // ],
            // [
            //     'name' => 'Yusuf',
            //     'arabic_name' => 'يوسف',
            //     'english_name' => 'Joseph',
            //     'meaning' => 'Joseph',
            // ],
            // [
            //     'name' => 'Ar-Ra\'d',
            //     'arabic_name' => 'الرعد',
            //     'english_name' => 'The Thunder',
            //     'meaning' => 'The Thunder',
            // ],
            // [
            //     'name' => 'Ibrahim',
            //     'arabic_name' => 'إبراهيم',
            //     'english_name' => 'Abraham',
            //     'meaning' => 'Abraham',
            // ],
            // [
            //     'name' => 'Al-Hijr',
            //     'arabic_name' => 'الحجر',
            //     'english_name' => 'The Rocky Tract',
            //     'meaning' => 'The Rocky Tract',
            // ],
            // [
            //     'name' => 'An-Nahl',
            //     'arabic_name' => 'النحل',
            //     'english_name' => 'The Bee',
            //     'meaning' => 'The Bee',
            // ],
            // [
            //     'name' => 'Al-Isra',
            //     'arabic_name' => 'الإسراء',
            //     'english_name' => 'The Night Journey',
            //     'meaning' => 'The Night Journey',
            // ],
            // [
            //     'name' => 'Al-Kahf',
            //     'arabic_name' => 'الكهف',
            //     'english_name' => 'The Cave',
            //     'meaning' => 'The Cave',
            // ],
            // [
            //     'name' => 'Maryam',
            //     'arabic_name' => 'مريم',
            //     'english_name' => 'Mary',
            //     'meaning' => 'Mary',
            // ],
            // [
            //     'name' => 'Ta-Ha',
            //     'arabic_name' => 'طه',
            //     'english_name' => 'Ta-Ha',
            //     'meaning' => 'Ta-Ha',
            // ],
            // [
            //     'name' => 'Al-Anbiya',
            //     'arabic_name' => 'الأنبياء',
            //     'english_name' => 'The Prophets',
            //     'meaning' => 'The Prophets',
            // ],
            // [
            //     'name' => 'Al-Hajj',
            //     'arabic_name' => 'الحج',
            //     'english_name' => 'The Pilgrimage',
            //     'meaning' => 'The Pilgrimage',
            // ],
            // [
            //     'name' => 'Al-Muminun',
            //     'arabic_name' => 'المؤمنون',
            //     'english_name' => 'The Believers',
            //     'meaning' => 'The Believers',
            // ],
            // [
            //     'name' => 'Az-Zumar',
            //     'arabic_name' => 'الزمر',
            //     'english_name' => 'The Troops',
            //     'meaning' => 'The Troops',
            // ],
            // [
            //     'name' => 'Ghafir',
            //     'arabic_name' => 'غافر',
            //     'english_name' => 'The Forgiver',
            //     'meaning' => 'The Forgiver',
            // ],
            // [
            //     'name' => 'Fussilat',
            //     'arabic_name' => 'فصلت',
            //     'english_name' => 'Explained in Detail',
            //     'meaning' => 'Explained in Detail',
            // ],
            // [
            //     'name' => 'Ash-Shura',
            //     'arabic_name' => 'الشورى',
            //     'english_name' => 'The Consultation',
            //     'meaning' => 'The Consultation',
            // ],
            // [
            //     'name' => 'Az-Zukhruf',
            //     'arabic_name' => 'الزخرف',
            //     'english_name' => 'The Ornaments of Gold',
            //     'meaning' => 'The Ornaments of Gold',
            // ],
            // [
            //     'name' => 'Ad-Dukhan',
            //     'arabic_name' => 'الدخان',
            //     'english_name' => 'The Smoke',
            //     'meaning' => 'The Smoke',
            // ],
            // [
            //     'name' => 'Al-Jathiyah',
            //     'arabic_name' => 'الجاثية',
            //     'english_name' => 'The Crouching',
            //     'meaning' => 'The Crouching',
            // ],
            // [
            //     'name' => 'Al-Ahqaf',
            //     'arabic_name' => 'الأحقاف',
            //     'english_name' => 'The Wind-Curved Sandhills',
            //     'meaning' => 'The Wind-Curved Sandhills',
            // ],
            // [
            //     'name' => 'Muhammad',
            //     'arabic_name' => 'محمد',
            //     'english_name' => 'Muhammad',
            //     'meaning' => 'Muhammad',
            // ],
            // [
            //     'name' => 'Al-Fath',
            //     'arabic_name' => 'الفتح',
            //     'english_name' => 'The Victory',
            //     'meaning' => 'The Victory',
            // ],
            // [
            //     'name' => 'Al-Hujurat',
            //     'arabic_name' => 'الحجرات',
            //     'english_name' => 'The Rooms',
            //     'meaning' => 'The Rooms',
            // ],
            // [
            //     'name' => 'Qaf',
            //     'arabic_name' => 'ق',
            //     'english_name' => 'Qaf',
            //     'meaning' => 'Qaf',
            // ],
            // [
            //     'name' => 'Ad-Dhariyat',
            //     'arabic_name' => 'الذاريات',
            //     'english_name' => 'The Scatterers',
            //     'meaning' => 'The Scatterers',
            // ],
            // [
            //     'name' => 'At-Tur',
            //     'arabic_name' => 'الطور',
            //     'english_name' => 'The Mount',
            //     'meaning' => 'The Mount',
            // ],
            // [
            //     'name' => 'An-Najm',
            //     'arabic_name' => 'النجم',
            //     'english_name' => 'The Star',
            //     'meaning' => 'The Star',
            // ],
            // [
            //     'name' => 'Al-Qamar',
            //     'arabic_name' => 'القمر',
            //     'english_name' => 'The Moon',
            //     'meaning' => 'The Moon',
            // ],
            // [
            //     'name' => 'Ar-Rahman',
            //     'arabic_name' => 'الرحمن',
            //     'english_name' => 'The Beneficent',
            //     'meaning' => 'The Beneficent',
            // ],
            // [
            //     'name' => 'Al-Waqi\'ah',
            //     'arabic_name' => 'الواقعة',
            //     'english_name' => 'The Inevitable',
            //     'meaning' => 'The Inevitable',
            // ],
            // [
            //     'name' => 'Al-Hadid',
            //     'arabic_name' => 'الحديد',
            //     'english_name' => 'The Iron',
            //     'meaning' => 'The Iron',
            // ],
            // [
            //     'name' => 'Al-Mujadila',
            //     'arabic_name' => 'المجادلة',
            //     'english_name' => 'Al Mujadila',
            //     'meaning' => 'Al Mujadila',
            // ],
            // [
            //     'name' => 'Al-Hashr',
            //     'arabic_name' => 'الحشر',
            //     'english_name' => 'The Exile',
            //     'meaning' => 'The Exile',
            // ],
            // [
            //     'name' => 'Al-Mumtahanah',
            //     'arabic_name' => 'الممتحنة',
            //     'english_name' => 'She that is to be examined',
            //     'meaning' => 'She that is to be examined',
            // ],
            // [
            //     'name' => 'As-Saff',
            //     'arabic_name' => 'الصف',
            //     'english_name' => 'The Ranks',
            //     'meaning' => 'The Ranks',
            // ],
            // [
            //     'name' => 'Al-Jumu\'ah',
            //     'arabic_name' => 'الجمعة',
            //     'english_name' => 'The Congregation',
            //     'meaning' => 'The Congregation',
            // ],
            // [
            //     'name' => 'Al-Munafiqun',
            //     'arabic_name' => 'المنافقون',
            //     'english_name' => 'The Hypocrites',
            //     'meaning' => 'The Hypocrites',
            // ],
            // [
            //     'name' => 'At-Taghabun',
            //     'arabic_name' => 'التغابن',
            //     'english_name' => 'The Manifestation of Losses',
            //     'meaning' => 'The Manifestation of Losses',
            // ],
            // [
            //     'name' => 'At-Talaq',
            //     'arabic_name' => 'الطلاق',
            //     'english_name' => 'Divorce',
            //     'meaning' => 'Divorce',
            // ],
            // [
            //     'name' => 'At-Tahrim',
            //     'arabic_name' => 'التحريم',
            //     'english_name' => 'The Prohibition',
            //     'meaning' => 'The Prohibition',
            // ],
            // [
            //     'name' => 'Al-Mulk',
            //     'arabic_name' => 'الملك',
            //     'english_name' => 'The Sovereignty',
            //     'meaning' => 'The Sovereignty',
            // ],
            // [
            //     'name' => 'Al-Qalam',
            //     'arabic_name' => 'القلم',
            //     'english_name' => 'The Pen',
            //     'meaning' => 'The Pen',
            // ],
            // [
            //     'name' => 'Al-Haqqah',
            //     'arabic_name' => 'الحاقة',
            //     'english_name' => 'The Reality',
            //     'meaning' => 'The Reality',
            // ],
            // [
            //     'name' => 'Al-Ma\'arij',
            //     'arabic_name' => 'المعارج',
            //     'english_name' => 'The Ascending Stairways',
            //     'meaning' => 'The Ascending Stairways',
            // ],
            // [
            //     'name' => 'Nuh',
            //     'arabic_name' => 'نوح',
            //     'english_name' => 'Noah',
            //     'meaning' => 'Noah',
            // ],
            // [
            //     'name' => 'Al-Jinn',
            //     'arabic_name' => 'الجن',
            //     'english_name' => 'The Jinn',
            //     'meaning' => 'The Jinn',
            // ],
            // [
            //     'name' => 'Al-Muzzammil',
            //     'arabic_name' => 'المزمل',
            //     'english_name' => 'The Enshrouded One',
            //     'meaning' => 'The Enshrouded One',
            // ],
            // [
            //     'name' => 'Al-Muddaththir',
            //     'arabic_name' => 'المدثر',
            //     'english_name' => 'The Cloaked One',
            //     'meaning' => 'The Cloaked One',
            // ],
            // [
            //     'name' => 'Al-Qiyamah',
            //     'arabic_name' => 'القيامة',
            //     'english_name' => 'The Resurrection',
            //     'meaning' => 'The Resurrection',
            // ],
            // [
            //     'name' => 'Al-Insan',
            //     'arabic_name' => 'الإنسان',
            //     'english_name' => 'Man',
            //     'meaning' => 'Man'
            // ]
        ];

        DB::table('suras')->insert($suras);

    }
}
