<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SuraTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // write seeder for suras table
        $suras = [
            [
                'name'                => 'Al-Fatihah',
                'arabic_name'         => 'الفاتحة',
                'english_name'        => 'The Opening',
                'bangla_text'         => 'আল-ফাতিহা',
                'meaning'             => 'সূচনা',
                'ayat_count'          => '7',
                'type'                => 'Meccan',
                'revelation_order'    => '5',
                'rukus'               => '1',
                'place_of_revelation' => 'Mecca',
                'status'              => 'active',
                'audio'               => 'https://server8.mp3quran.net/basit/001.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3YpLj8',
                'image'               => 'https://i.ytimg.com/vi/VHfJY3YpLj8/maxresdefault.jpg',
            ],
            [
                'name'                => 'Al-Baqarah',
                'arabic_name'         => 'البقرة',
                'english_name'        => 'The Cow',
                'bangla_text'         => 'আল-বাকারা',
                'meaning'             => 'গাভী',
                'ayat_count'          => '286',
                'type'                => 'Medinan',
                'revelation_order'    => '87',
                'rukus'               => '40',
                'place_of_revelation' => 'Medina',
                'status'              => 'active',
                'audio'               => 'https://server8.mp3quran.net/basit/002.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3YpLj8',
                'image'               => 'https://i.ytimg.com/vi/VHfJY3YpLj8/maxresdefault.jpg',
            ],
            [
                'name'                => 'Aal-E-Imran',
                'arabic_name'         => 'آل عمران',
                'english_name'        => 'The Family of Imran',
                'bangla_text'         => 'আল-ইমরান',
                'meaning'             => 'ইমরানের পরিবার',
                'ayat_count'          => '200',
                'type'                => 'Medinan',
                'revelation_order'    => '89',
                'rukus'               => '20',
                'place_of_revelation' => 'Medina',
                'status'              => 'active',
                'audio'               => 'https://server8.mp3quran.net/basit/003.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3YpLj8',
                'image'               => 'https://i.ytimg.com/vi/VHfJY3YpLj8/maxresdefault.jpg',
            ],
            [
                'name'                => 'An-Nisa',
                'arabic_name'         => 'النساء',
                'english_name'        => 'The Women',
                'bangla_text'         => 'আন-নিসা',
                'meaning'             => 'The Women',
                'ayat_count'          => '176',
                'type'                => 'Medinan',
                'revelation_order'    => '92',
                'rukus'               => '24',
                'place_of_revelation' => 'Medina',
                'status'              => 'active',
                'audio'               => 'https://server8.mp3quran.net/basit/004.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3YpLj8',
                'image'               => 'https://i.ytimg.com/vi/VHfJY3YpLj8/maxresdefault.jpg',
            ],
            [
                'name'                => 'Al-Ma\'idah',
                'arabic_name'         => 'المائدة',
                'english_name'        => 'The Table Spread',
                'bangla_text'         => 'আল-মা’ইদাহ',
                'meaning'             => 'Ma\'idah',
                'ayat_count'          => '120',
                'type'                => 'Medinan',
                'revelation_order'    => '112',
                'rukus'               => '16',
                'place_of_revelation' => 'Medina',
                'status'              => 'active',
                'audio'               => 'https://server8.mp3quran.net/basit/005.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3YpLj8',
                'image'               => 'https://i.ytimg.com/vi/VHfJY3YpLj8/maxresdefault.jpg',
            ],
            [
                'name'                => 'Al-An\'am',
                'arabic_name'         => 'الأنعام',
                'english_name'        => 'The Cattle',
                'bangla_text'         => 'আল-আনআম',
                'meaning'             => 'পশু',
                'ayat_count'          => '165',
                'type'                => 'Meccan',
                'revelation_order'    => '55',
                'rukus'               => '20',
                'place_of_revelation' => 'Mecca',
                'status'              => 'active',
                'audio'               => 'https://server8.mp3quran.net/basit/006.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3YpLj8',
                'image'               => 'https://i.ytimg.com/vi/VHfJY3YpLj8/maxresdefault.jpg',
            ],
            [
                'name'                => 'Al-A\'raf',
                'arabic_name'         => 'الأعراف',
                'english_name'        => 'The Heights',
                'bangla_text'         => 'আল-আরাফ',
                'meaning'             => 'আরাফ',
                'ayat_count'          => '206',
                'type'                => 'Meccan',
                'revelation_order'    => '39',
                'rukus'               => '24',
                'place_of_revelation' => 'Mecca',
                'status'              => 'active',
                'audio'               => 'https://server8.mp3quran.net/basit/007.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3YpLj8',
                'image'               => 'https://i.ytimg.com/vi/VHfJY3YpLj8/maxresdefault.jpg',
            ],
            [
                'name'                => 'Al-Anfal',
                'arabic_name'         => 'الأنفال',
                'english_name'        => 'The Spoils of War',
                'bangla_text'         => 'আল-আনফাল',
                'meaning'             => 'আনফাল',
                'ayat_count'          => '75',
                'type'                => 'Medinan',
                'revelation_order'    => '88',
                'rukus'               => '10',
                'place_of_revelation' => 'Medina',
                'status'              => 'active',
                'audio'               => 'https://server8.mp3quran.net/basit/008.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3YpLj8',
                'image'               => 'https://i.ytimg.com/vi/VHfJY3YpLj8/maxresdefault.jpg',
            ],
            [
                'name'                => 'At-Tawbah',
                'arabic_name'         => 'التوبة',
                'english_name'        => 'The Repentance',
                'bangla_text'         => 'আত-তাওবা',
                'meaning'             => 'পশ্চাতাপ',
                'ayat_count'          => '129',
                'type'                => 'Medinan',
                'revelation_order'    => '113',
                'rukus'               => '16',
                'place_of_revelation' => 'Medina',
                'status'              => 'active',
                'audio'               => 'https://server8.mp3quran.net/basit/009.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3YpLj8',
                'image'               => 'https://i.ytimg.com/vi/VHfJY3YpLj8/maxresdefault.jpg',

            ],
            [
                'name'                => 'Yunus',
                'arabic_name'         => 'يونس',
                'bangla_text'         => 'ইউনুস',
                'meaning'             => 'ইউনুস',
                'english_name'        => 'Jonah',
                'ayat_count'          => '109',
                'type'                => 'Meccan',
                'revelation_order'    => '51',
                'rukus'               => '11',
                'place_of_revelation' => 'Mecca',
                'status'              => 'active',
                'audio'               => 'https://server8.mp3quran.net/basit/010.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3YpLj8',
                'image'               => '',
            ],
            [
                'name'                => 'Hud',
                'arabic_name'         => 'هود',
                'english_name'        => 'Hud',
                'bangla_text'         => 'হুদ',
                'meaning'             => 'হুদ',
                'ayat_count'          => '123',
                'type'                => 'Meccan',
                'revelation_order'    => '52',
                'rukus'               => '10',
                'place_of_revelation' => 'Mecca',
                'status'              => 'active',
                'audio'               => 'https://server8.mp3quran.net/basit/011.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3Yp',
                'image'               => '',
            ],
            [
                'name'                => 'Yusuf',
                'arabic_name'         => 'يوسف',
                'english_name'        => 'Joseph',
                'bangla_text'         => 'ইউসুফ',
                'meaning'             => 'ইউসুফ',
                'ayat_count'          => '111',
                'type'                => 'Meccan',
                'revelation_order'    => '53',
                'rukus'               => '12',
                'place_of_revelation' => 'Mecca',
                'status'              => 'active',
                'audio'               => 'https://server8.mp3quran.net/basit/012.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3Yp',
                'image'               => '',
            ],
            [
                'name'                => 'Ar-Ra\'d',
                'arabic_name'         => 'الرعد',
                'english_name'        => 'The Thunder',
                'bangla_text'         => 'আর-রা’দ',
                'meaning'             => 'বজ্রপাত',
                'ayat_count'          => '43',
                'type'                => 'Medinan',
                'revelation_order'    => '96',
                'rukus'               => '6',
                'place_of_revelation' => 'Medina',
                'status'              => 'active',
                'audio'               => 'https://server8.mp3quran.net/basit/013.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3Yp',
                'image'               => '',
            ],
            [
                'name'                => 'Ibrahim',
                'arabic_name'         => 'إبراهيم',
                'english_name'        => 'Abraham',
                'bangla_text'         => 'ইব্রাহীম',
                'meaning'             => 'ইব্রাহীম',
                'ayat_count'          => '52',
                'type'                => 'Meccan',
                'revelation_order'    => '72',
                'rukus'               => '7',
                'place_of_revelation' => 'Mecca',
                'status'              => 'active',
                'audio'               => 'https://server8.mp3quran.net/basit/014.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3Yp',
                'image'               => '',
            ],
            [
                'name'                => 'Al-Hijr',
                'arabic_name'         => 'الحجر',
                'english_name'        => 'The Rocky Tract',
                'bangla_text'         => 'আল-হিজর',
                'meaning'             => 'পাথরের প্রান্ত',
                'ayat_count'          => '99',
                'type'                => 'Meccan',
                'revelation_order'    => '54',
                'rukus'               => '6',
                'place_of_revelation' => 'Mecca',
                'status'              => 'active',
                'audio'               => 'https://server8.mp3quran.net/basit/015.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3Yp',
                'image'               => '',
            ],
            [
                'name'                => 'An-Nahl',
                'arabic_name'         => 'النحل',
                'english_name'        => 'The Bee',
                'bangla_text'         => 'আন-নাহল',
                'meaning'             => 'মৌমাছি',
                'ayat_count'          => '128',
                'type'                => 'Meccan',
                'revelation_order'    => '70',
                'rukus'               => '16',
                'place_of_revelation' => 'Mecca',
                'status'              => 'active',
                'audio'               => 'https://server8.mp3quran.net/basit/016.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3Yp',
                'image'               => '',
            ],
            [
                'name'                => 'Al-Isra',
                'arabic_name'         => 'الإسراء',
                'english_name'        => 'The Night Journey',
                'bangla_text'         => 'আল-ইসরা',
                'meaning'             => 'রাতের ভ্রমণ',
                'ayat_count'          => '111',
                'type'                => 'Meccan',
                'revelation_order'    => '50',
                'rukus'               => '12',
                'place_of_revelation' => 'Mecca',
                'status'              => 'active',
                'audio'               => 'https://server8.mp3quran.net/basit/017.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3Yp',
                'image'               => '',
            ],
            [
                'name'                => 'Al-Kahf',
                'arabic_name'         => 'الكهف',
                'english_name'        => 'The Cave',
                'bangla_text'         => 'আল-কাহফ',
                'meaning'             => 'গুহা',
                'ayat_count'          => '110',
                'type'                => 'Meccan',
                'revelation_order'    => '69',
                'rukus'               => '12',
                'place_of_revelation' => 'Mecca',
                'status'              => 'active',
                'audio'               => 'https://server8.mp3quran.net/basit/018.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3Yp',
                'image'               => '',
            ],
            [
                'name'                => 'Maryam',
                'arabic_name'         => 'مريم',
                'english_name'        => 'Mary',
                'bangla_text'         => 'মারিয়াম',
                'meaning'             => 'মেরি',
                'ayat_count'          => '98',
                'type'                => 'Meccan',
                'revelation_order'    => '44',
                'rukus'               => '6',
                'place_of_revelation' => 'Mecca',
                'status'              => 'active',
                'audio'               => 'https://server8.mp3quran.net/basit/019.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3Yp',
                'image'               => '',
            ],
            [
                'name'                => 'Ta-Ha',
                'arabic_name'         => 'طه',
                'english_name'        => 'Ta-Ha',
                'bangla_text'         => 'তা-হা',
                'meaning'             => 'তা-হা',
                'ayat_count'          => '135',
                'type'                => 'Meccan',
                'revelation_order'    => '45',
                'rukus'               => '8',
                'place_of_revelation' => 'Mecca',
                'status'              => 'active',
                'audio'               => 'https://server8.mp3quran.net/basit/020.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3Yp',
                'image'               => '',
            ],
            [
                'name'                => 'Al-Anbiya',
                'arabic_name'         => 'الأنبياء',
                'english_name'        => 'The Prophets',
                'bangla_text'         => 'আল-আনবিয়া',
                'meaning'             => 'প্রফেট',
                'ayat_count'          => '112',
                'type'                => 'Meccan',
                'revelation_order'    => '73',
                'rukus'               => '7',
                'place_of_revelation' => 'Mecca',
                'status'              => 'active',
                'audio'               => 'https://server8.mp3quran.net/basit/021.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3Yp',
                'image'               => '',
            ],
            [
                'name'                => 'Al-Hajj',
                'arabic_name'         => 'الحج',
                'english_name'        => 'The Pilgrimage',
                'bangla_text'         => 'আল-হাজ্জ',
                'meaning'             => 'হজ্জ',
                'ayat_count'          => '78',
                'type'                => 'Medinan',
                'revelation_order'    => '103',
                'rukus'               => '10',
                'place_of_revelation' => 'Medina',
                'status'              => 'active',
                'audio'               => 'https://server8.mp3quran.net/basit/022.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3Yp',
                'image'               => '',
            ],

            [
                'name'                => 'Al-Muminun',
                'arabic_name'         => 'المؤمنون',
                'english_name'        => 'The Believers',
                'bangla_text'         => 'আল-মুমিনুন',
                'meaning'             => 'বিশ্বাসী',
                'ayat_count'          => '118',
                'type'                => 'Meccan',
                'revelation_order'    => '74',
                'rukus'               => '6',
                'place_of_revelation' => 'Mecca',
                'status'              => 'active',
                'audio'               => 'https://server8.mp3quran.net/basit/023.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3Yp',
                'image'               => '',
            ],
            [
                'name'                => 'Az-Zumar',
                'arabic_name'         => 'الزمر',
                'english_name'        => 'The Troops',
                'bangla_text'         => 'আয-জুমার',
                'meaning'             => 'সেনা',
                'ayat_count'          => '75',
                'type'                => 'Meccan',
                'revelation_order'    => '102',
                'rukus'               => '8',
                'place_of_revelation' => 'Mecca',
                'status'              => 'active',
                'audio'               => 'https://server8.mp3quran.net/basit/024.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3Yp',
                'image'               => '',
            ],

            [
                'name'                => 'Ghafir',
                'arabic_name'         => 'غافر',
                'english_name'        => 'The Forgiver',
                'bangla_text'         => 'গাফির',
                'meaning'             => 'ক্ষমাশীল',
                'ayat_count'          => '85',
                'type'                => 'Meccan',
                'revelation_order'    => '42',
                'rukus'               => '9',
                'place_of_revelation' => 'Mecca',
                'status'              => 'active',
                'audio'               => 'https://server8.mp3quran.net/basit/025.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3Yp',
                'image'               => '',
            ],

            [
                'name'                => 'Fussilat',
                'arabic_name'         => 'فصلت',
                'english_name'        => 'Explained in Detail',
                'bangla_text'         => 'ফুসসিলাত',
                'meaning'             => 'বিস্তারিত',
                'ayat_count'          => '54',
                'type'                => 'Meccan',
                'revelation_order'    => '47',
                'rukus'               => '6',
                'place_of_revelation' => 'Mecca',
                'status'              => 'active',
                'audio'               => 'https://server8.mp3quran.net/basit/026.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3Yp',
                'image'               => '',
            ],
            [
                'name'                => 'Ash-Shura',
                'arabic_name'         => 'الشورى',
                'english_name'        => 'The Consultation',
                'bangla_text'         => 'আশ-শুরা',
                'meaning'             => 'পরামর্শ',
                'ayat_count'          => '53',
                'type'                => 'Meccan',
                'revelation_order'    => '48',
                'rukus'               => '5',
                'place_of_revelation' => 'Mecca',
                'status'              => 'active',
                'audio'               => 'https://server8.mp3quran.net/basit/027.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3Yp',
                'image'               => '',
            ],

            [
                'name'                => 'Az-Zukhruf',
                'arabic_name'         => 'الزخرف',
                'english_name'        => 'The Ornaments of Gold',
                'bangla_text'         => 'আয-জুখরুফ',
                'meaning'             => 'স্বর্ণমূল্য',
                'ayat_count'          => '89',
                'type'                => 'Meccan',
                'revelation_order'    => '49',
                'rukus'               => '7',
                'place_of_revelation' => 'Mecca',
                'status'              => 'active',
                'audio'               => 'https://server8.mp3quran.net/basit/028.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3Yp',
                'image'               => '',
            ],

            [
                'name'                => 'Ad-Dukhan',
                'arabic_name'         => 'الدخان',
                'english_name'        => 'The Smoke',
                'bangla_text'         => 'আদ-দুখান',
                'meaning'             => 'ধোঁয়া',
                'ayat_count'          => '59',
                'type'                => 'Meccan',
                'revelation_order'    => '85',
                'rukus'               => '3',
                'place_of_revelation' => 'Mecca',
                'status'              => 'active',
                'audio'               => 'https://server8.mp3quran.net/basit/029.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3Yp',
                'image'               => '',
            ],
            [
                'name'                => 'Al-Jathiyah',
                'arabic_name'         => 'الجاثية',
                'english_name'        => 'The Crouching',
                'bangla_text'         => 'আল-জাথিয়া',
                'meaning'             => 'মুড়ানো',
                'ayat_count'          => '37',
                'type'                => 'Meccan',
                'revelation_order'    => '84',
                'rukus'               => '4',
                'place_of_revelation' => 'Mecca',
                'status'              => 'active',
                'audio'               => 'https://server8.mp3quran.net/basit/045.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3Yp',
                'image'               => '',
            ],

            [
                'name'                => 'Al-Ahqaf',
                'arabic_name'         => 'الأحقاف',
                'english_name'        => 'The Wind-Curved Sandhills',
                'bangla_text'         => 'আল-আহকাফ',
                'meaning'             => 'বাতাস-মোড়ানো বালুমুখ',
                'ayat_count'          => '35',
                'type'                => 'Meccan',
                'revelation_order'    => '57',
                'rukus'               => '4',
                'place_of_revelation' => 'Mecca',
                'status'              => 'active',
                'audio'               => 'https://cdn.islamic.network/quran/audio/128/ar.basit/046.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3Yp',
                'image'               => '',
            ],

            [
                'name'                => 'Muhammad',
                'arabic_name'         => 'محمد',
                'english_name'        => 'Muhammad',
                'bangla_text'         => 'মুহাম্মদ',
                'meaning'             => 'মুহাম্মদ',
                'ayat_count'          => '38',
                'type'                => 'Medinan',
                'revelation_order'    => '96',
                'rukus'               => '4',
                'place_of_revelation' => 'Medina',
                'status'              => 'active',
                'audio'               => 'https://cdn.islamic.network/quran/audio/128/ar.basit/047.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3Yp',
                'image'               => '',
            ],
            [
                'name'                => 'Al-Fath',
                'arabic_name'         => 'الفتح',
                'english_name'        => 'The Victory',
                'bangla_text'         => 'আল-ফাতেহ',
                'meaning'             => 'বিজয়',
                'ayat_count'          => '29',
                'type'                => 'Medinan',
                'revelation_order'    => '94',
                'rukus'               => '4',
                'place_of_revelation' => 'Medina',
                'status'              => 'active',
                'audio'               => 'https://cdn.islamic.network/quran/audio/128/ar.basit/048.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3Yp',
                'image'               => '',
            ],

            [
                'name'                => 'Al-Hujurat',
                'arabic_name'         => 'الحجرات',
                'english_name'        => 'The Rooms',
                'bangla_text'         => 'আল-হুজুরাত',
                'meaning'             => 'কক্ষ',
                'ayat_count'          => '18',
                'type'                => 'Medinan',
                'revelation_order'    => '105',
                'rukus'               => '2',
                'place_of_revelation' => 'Medina',
                'status'              => 'active',
                'audio'               => 'https://cdn.islamic.network/quran/audio/128/ar.basit/049.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3Yp',
                'image'               => '',
            ],

            [
                'name'                => 'Qaf',
                'arabic_name'         => 'ق',
                'english_name'        => 'Qaf',
                'bangla_text'         => 'কাফ',
                'meaning'             => 'কাফ',
                'ayat_count'          => '45',
                'type'                => 'Meccan',
                'revelation_order'    => '43',
                'rukus'               => '3',
                'place_of_revelation' => 'Mecca',
                'status'              => 'active',
                'audio'               => 'https://cdn.islamic.network/quran/audio/128/ar.basit/050.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3Yp',
                'image'               => '',
            ],
            [
                'name'                => 'Adh-Dhariyat',
                'arabic_name'         => 'الذاريات',
                'english_name'        => 'The Winnowing Winds',
                'bangla_text'         => 'আদ-দাহরিয়াত',
                'meaning'             => 'বায়ু ছানা',
                'ayat_count'          => '60',
                'type'                => 'Meccan',
                'revelation_order'    => '41',
                'rukus'               => '3',
                'place_of_revelation' => 'Mecca',
                'status'              => 'active',
                'audio'               => 'https://cdn.islamic.network/quran/audio/128/ar.basit/051.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3Yp',
                'image'               => '',
            ],

            [
                'name'                => 'At-Tur',
                'arabic_name'         => 'الطور',
                'english_name'        => 'The Mount',
                'bangla_text'         => 'আত-তূর',
                'meaning'             => 'পর্বত',
                'ayat_count'          => '49',
                'type'                => 'Meccan',
                'revelation_order'    => '88',
                'rukus'               => '2',
                'place_of_revelation' => 'Mecca',
                'status'              => 'active',
                'audio'               => 'https://cdn.islamic.network/quran/audio/128/ar.basit/052.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3Yp',
                'image'               => '',
            ],

            [
                'name'                => 'An-Najm',
                'arabic_name'         => 'النجم',
                'english_name'        => 'The Star',
                'bangla_text'         => 'আন-নাজম',
                'meaning'             => 'তারা',
                'ayat_count'          => '62',
                'type'                => 'Meccan',
                'revelation_order'    => '66',
                'rukus'               => '3',
                'place_of_revelation' => 'Mecca',
                'status'              => 'active',
                'audio'               => 'https://cdn.islamic.network/quran/audio/128/ar.basit/053.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3Yp',
                'image'               => '',
            ],
            [
                'name'                => 'Al-Qamar',
                'arabic_name'         => 'القمر',
                'english_name'        => 'The Moon',
                'bangla_text'         => 'আল-কামার',
                'meaning'             => 'চাঁদ',
                'ayat_count'          => '55',
                'type'                => 'Meccan',
                'revelation_order'    => '95',
                'rukus'               => '3',
                'place_of_revelation' => 'Mecca',
                'status'              => 'active',
                'audio'               => 'https://cdn.islamic.network/quran/audio/128/ar.basit/054.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3Yp',
                'image'               => '',
            ],

            [
                'name'                => 'Ar-Rahman',
                'arabic_name'         => 'الرحمن',
                'english_name'        => 'The Beneficent',
                'bangla_text'         => 'আর-রহমান',
                'meaning'             => 'মেহেরবান',
                'ayat_count'          => '78',
                'type'                => 'Medinan',
                'revelation_order'    => '88',
                'rukus'               => '3',
                'place_of_revelation' => 'Medina',
                'status'              => 'active',
                'audio'               => 'https://cdn.islamic.network/quran/audio/128/ar.basit/055.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3Yp',
                'image'               => '',
            ],

            [
                'name'                => 'Al-Waqi\'ah',
                'arabic_name'         => 'الواقعة',
                'english_name'        => 'The Inevitable',
                'bangla_text'         => 'আল-ওয়াকিয়া',
                'meaning'             => 'অবশ্যই ঘটবে',
                'ayat_count'          => '96',
                'type'                => 'Meccan',
                'revelation_order'    => '67',
                'rukus'               => '3',
                'place_of_revelation' => 'Mecca',
                'status'              => 'active',
                'audio'               => 'https://cdn.islamic.network/quran/audio/128/ar.basit/056.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3Yp',
                'image'               => '',
            ],
            [
                'name'                => 'Al-Hadid',
                'arabic_name'         => 'الحديد',
                'english_name'        => 'The Iron',
                'bangla_text'         => 'আল-হাদিদ',
                'meaning'             => 'লোহা',
                'ayat_count'          => '29',
                'type'                => 'Medinan',
                'revelation_order'    => '76',
                'rukus'               => '4',
                'place_of_revelation' => 'Medina',
                'status'              => 'active',
                'audio'               => 'https://cdn.islamic.network/quran/audio/128/ar.basit/057.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3Yp',
                'image'               => '',
            ],
            [
                'name'                => 'Al-Mujadila',
                'arabic_name'         => 'المجادلة',
                'english_name'        => 'Al-Mujadila',
                'bangla_text'         => 'আল-মুজাদিলা',
                'meaning'             => 'মুজাদিলা',
                'ayat_count'          => '22',
                'type'                => 'Medinan',
                'revelation_order'    => '83',
                'rukus'               => '3',
                'place_of_revelation' => 'Medina',
                'status'              => 'active',
                'audio'               => 'https://cdn.islamic.network/quran/audio/128/ar.basit/058.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3Yp',
                'image'               => '',
            ],
            [
                'name'                => 'Al-Hashr',
                'arabic_name'         => 'الحشر',
                'english_name'        => 'The Exile',
                'bangla_text'         => 'আল-হাশর',
                'meaning'             => 'বিসর্জন',
                'ayat_count'          => '24',
                'type'                => 'Medinan',
                'revelation_order'    => '27',
                'rukus'               => '3',
                'place_of_revelation' => 'Medina',
                'status'              => 'active',
                'audio'               => 'https://cdn.islamic.network/quran/audio/128/ar.basit/059.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3Yp',
                'image'               => '',
            ],
            [
                'name'                => '\'Al-Mumtahanah',
                'arabic_name'         => 'الممتحنة',
                'english_name'        => 'She that is to be examined',
                'bangla_text'         => 'আল-মুমতাহানা',
                'meaning'             => 'পরীক্ষা করা হবে',
                'ayat_count'          => '13',
                'type'                => 'Medinan',
                'revelation_order'    => '101',
                'rukus'               => '2',
                'place_of_revelation' => 'Medina',
                'status'              => 'active',
                'audio'               => 'https://cdn.islamic.network/quran/audio/128/ar.basit/060.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3Yp',
                'image'               => '',
            ],
            [
                'name'                => '\'As-Saff',
                'arabic_name'         => 'الصف',
                'english_name'        => 'The Ranks',
                'bangla_text'         => 'আস-সাফ',
                'meaning'             => 'সারি',
                'ayat_count'          => '14',
                'type'                => 'Medinan',
                'revelation_order'    => '91',
                'rukus'               => '2',
                'place_of_revelation' => 'Medina',
                'status'              => 'active',
                'audio'               => 'https://cdn.islamic.network/quran/audio/128/ar.basit/061.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3Yp',
                'image'               => '',
            ],

            [
                'name'                => 'Al-Jumu\'ah',
                'arabic_name'         => 'الجمعة',
                'english_name'        => 'The Congregation',
                'bangla_text'         => 'আল-জুমুআ',
                'meaning'             => 'জুমুআ',
                'ayat_count'          => '11',
                'type'                => 'Medinan',
                'revelation_order'    => '106',
                'rukus'               => '2',
                'place_of_revelation' => 'Medina',
                'status'              => 'active',
                'audio'               => 'https://cdn.islamic.network/quran/audio/128/ar.basit/062.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3Yp',
                'image'               => '',
            ],

            [
                'name'                => '\'Al-Munafiqun',
                'arabic_name'         => 'المنافقون',
                'english_name'        => 'The Hypocrites',
                'bangal_text'         => 'আল-মুনাফিকুন',
                'meaning'             => 'মুনাফিক',
                'ayat_count'          => '11',
                'type'                => 'Medinan',
                'revelation_order'    => '104',
                'rukus'               => '2',
                'place_of_revelation' => 'Medina',
                'status'              => 'active',
                'audio'               => 'https://cdn.islamic.network/quran/audio/128/ar.basit/063.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3Yp',
                'image'               => '',
            ],

            [
                'name'                => '\'At-Taghabun',
                'arabic_name'         => 'التغابن',
                'english_name'        => 'Mutual Disillusion',
                'bangla_text'         => 'আত-তাগাবুন',
                'meaning'             => 'প্রতিপাদন',
                'ayat_count'          => '18',
                'type'                => 'Medinan',
                'revelation_order'    => '108',
                'rukus'               => '2',
                'place_of_revelation' => 'Medina',
                'status'              => 'active',
                'audio'               => 'https://cdn.islamic.network/quran/audio/128/ar.basit/064.mp3',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3Yp',
                'image'               => '',
            ],
            [
                'name'                => '\'At-Talaq',
                'arabic_name'         => 'الطلاق',
                'english_name'        => 'Divorce',
                'bangla_text'         => 'আত-তালাক',
                'meaning'             => 'তালাক',
                'ayat_count'          => '12',
                'type'                => 'Medinan',
                'revelation_order'    => '99',
                'rukus'               => '2',
                'place_of_revelation' => 'Medina',
                'status'              => 'active',
                'audio'               => '',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3Yp',
                'image'               => '',
            ],

            [
                'name'                => '\'At-Tahrim',
                'arabic_name'         => 'التحريم',
                'english_name'        => 'The Prohibition',
                'bangla_text'         => 'আত-তাহরীম',
                'meaning'             => 'নিষেধ',
                'ayat_count'          => '12',
                'type'                => 'Medinan',
                'revelation_order'    => '107',
                'rukus'               => '2',
                'place_of_revelation' => 'Medina',
                'status'              => 'active',
                'audio'               => '',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3Yp',
                'image'               => '',
            ],

            [
                'name'                => 'Al-Mulk',
                'arabic_name'         => 'الملك',
                'english_name'        => 'The Sovereignty',
                'bangla_text'         => 'আল-মুলক',
                'meaning'             => 'রাজ্য',
                'ayat_count'          => '30',
                'type'                => 'Meccan',
                'revelation_order'    => '77',
                'rukus'               => '2',
                'place_of_revelation' => 'Mecca',
                'status'              => 'active',
                'audio'               => '',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3Yp',
                'image'               => '',
            ],

            [
                'name'                => 'Al-Qalam',
                'arabic_name'         => 'القلم',
                'english_name'        => 'The Pen',
                'bangla_text'         => 'আল-কালাম',
                'meaning'             => 'কলম',
                'ayat_count'          => '52',
                'type'                => 'Meccan',
                'revelation_order'    => '2',
                'rukus'               => '2',
                'place_of_revelation' => 'Mecca',
                'status'              => 'active',
                'audio'               => '',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3Yp',
                'image'               => '',
            ],
            [
                'name'                => 'Al-Haqqah',
                'arabic_name'         => 'الحاقة',
                'english_name'        => 'The Reality',
                'bangla_text'         => 'আল-হাক্কা',
                'meaning'             => 'সত্য',
                'ayat_count'          => '52',
                'type'                => 'Meccan',
                'revelation_order'    => '78',
                'rukus'               => '2',
                'place_of_revelation' => 'Mecca',
                'status'              => 'active',
                'audio'               => '',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3Yp',
                'image'               => '',
            ],

            [
                'name'                => 'Al-Ma\'arij',
                'arabic_name'         => 'المعارج',
                'english_name'        => 'The Ascending Stairways',
                'bangla_text'         => 'আল-মা\'রিজ',
                'meaning'             => 'উচ্চতা',
                'ayat_count'          => '44',
                'type'                => 'Meccan',
                'revelation_order'    => '79',
                'rukus'               => '2',
                'place_of_revelation' => 'Mecca',
                'status'              => 'active',
                'audio'               => '',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3Yp',
                'image'               => '',
            ],
            [
                'name'                => 'Nuh',
                'arabic_name'         => 'نوح',
                'english_name'        => 'Noah',
                'bangla_text'         => 'নূহ',
                'meaning'             => 'নূহ',
                'ayat_count'          => '28',
                'type'                => 'Meccan',
                'revelation_order'    => '71',
                'rukus'               => '2',
                'place_of_revelation' => 'Mecca',
                'status'              => 'active',
                'audio'               => '',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3Yp',
                'image'               => '',
            ],
            [
                'name'                => 'Al-Jinn',
                'arabic_name'         => 'الجن',
                'english_name'        => 'The Jinn',
                'bangla_text'         => 'আল-জিন্ন',
                'meaning'             => 'জিন্ন',
                'ayat_count'          => '28',
                'type'                => 'Meccan',
                'revelation_order'    => '40',
                'rukus'               => '2',
                'place_of_revelation' => 'Mecca',
                'status'              => 'active',
                'audio'               => '',
                'video'               => 'https://www.youtube.com/watch?v=VHfJY3Yp',
                'image'               => '',
            ],

            [
                'name'                => 'Al-Muzzammil',
                'arabic_name'         => 'المزمل',
                'meaning'             => 'The One Covering Himself',
                'english_name'        => 'The Enshrouded One',
                'bangla_text'         => 'আল-মুজাম্মিল',
                'meaning'             => 'তারা',
                'ayat_count'          => '20',
                'type'                => 'Makki',
                'revelation_order'    => '73',
                'rukus'               => '2',
                'place_of_revelation' => 'Makkah',
                'status'              => 'active',
                'audio'               => 'audio_url_for_Al_Muzzammil',
                'video'               => 'video_url_for_Al_Muzzammil',
                'image'               => 'image_url_for_Al_Muzzammil',
            ],
            [
                'name'                => 'Al-Muddathir',
                'arabic_name'         => 'المدثر',
                'bangla_text'         => 'আল-মুদ্দাসির',
                'meaning'             => 'পোশাক পরিধান',
                'english_name'        => 'The Cloaked One',
                'ayat_count'          => '56',
                'type'                => 'Makki',
                'revelation_order'    => '2',
                'rukus'               => '2',
                'place_of_revelation' => 'Makkah',
                'status'              => 'active',
                'audio'               => 'audio_url_for_Al_Muddathir',
                'video'               => 'video_url_for_Al_Muddathir',
                'image'               => 'image_url_for_Al_Muddathir',
            ],
            [
                'name'                => 'Al-Qiyamah',
                'arabic_name'         => 'القيامة',
                'english_name'        => 'The Resurrection',
                'bangla_text'         => 'আল-কিয়ামাহ',
                'meaning'             => 'পুনরুত্থান',
                'ayat_count'          => '40',
                'type'                => 'Makki',
                'revelation_order'    => '75',
                'rukus'               => '1',
                'place_of_revelation' => 'Makkah',
                'status'              => 'active',
                'audio'               => 'audio_url_for_Al_Qiyamah',
                'video'               => 'video_url_for_Al_Qiyamah',
                'image'               => 'image_url_for_Al_Qiyamah',
            ],
            [
                'name'                => 'Al-Insan',
                'arabic_name'         => 'الإنسان',
                'meaning'             => 'The Man',
                'english_name'        => 'The Human',
                'bangla_text'         => 'আল-ইনসান',
                'meaning'             => 'মানুষ',
                'ayat_count'          => '31',
                'type'                => 'Madani',
                'revelation_order'    => '76',
                'rukus'               => '3',
                'place_of_revelation' => 'Madina',
                'status'              => 'active',
                'audio'               => 'audio_url_for_Al_Insan',
                'video'               => 'video_url_for_Al_Insan',
                'image'               => 'image_url_for_Al_Insan',
            ],
            [
                'name'                => 'Al-Mursalaat',
                'arabic_name'         => 'المرسلات',
                'bangla_text'         => 'প্রেরিত করা',
                'english_name'        => 'The Emissaries',
                'bangla_text'         => 'আল-মুরসালাত',
                'meaning'             => 'প্রেরিত করা',
                'ayat_count'          => '50',
                'type'                => 'Makki',
                'revelation_order'    => '77',
                'rukus'               => '2',
                'place_of_revelation' => 'Makkah',
                'status'              => 'active',
                'audio'               => 'audio_url_for_Al_Mursalaat',
                'video'               => 'video_url_for_Al_Mursalaat',
                'image'               => 'image_url_for_Al_Mursalaat',
            ],
            [
                'name'                => 'An-Naba',
                'arabic_name'         => 'النبأ',
                'bangla_text'         => 'খবর',
                'english_name'        => 'The Tidings',
                'bangla_text'         => 'আন-নাবা',
                'meaning'             => 'খবর',
                'ayat_count'          => '40',
                'type'                => 'Makki',
                'revelation_order'    => '78',
                'rukus'               => '2',
                'place_of_revelation' => 'Makkah',
                'status'              => 'active',
                'audio'               => 'audio_url_for_An_Naba',
                'video'               => 'video_url_for_An_Naba',
                'image'               => 'image_url_for_An_Naba',
            ],
            [
                'name'                => 'An-Nazi\'at',
                'arabic_name'         => 'النازعات',
                'bangla_text'         => 'আন-নাজিয়াত',
                'meaning'             => 'প্রক্ষিপ্ত করা',
                'english_name'        => 'The Chargers',
                'ayat_count'          => '46',
                'type'                => 'Makki',
                'revelation_order'    => '79',
                'rukus'               => '2',
                'place_of_revelation' => 'Makkah',
                'status'              => 'active',
                'audio'               => 'audio_url_for_An_Naziat',
                'video'               => 'video_url_for_An_Naziat',
                'image'               => 'image_url_for_An_Naziat',
            ],
            [
                'name'                => 'Abasa',
                'arabic_name'         => 'عَبَسَ',
                'bangla_name'         => 'আবাসা',
                'meaning'             => 'He Frowned',
                'english_name'        => 'The Overthrowing',
                'ayat_count'          => '42',
                'type'                => 'Makki',
                'revelation_order'    => '80',
                'rukus'               => '1',
                'place_of_revelation' => 'Mecca',
                'status'              => 'Makki',
                'audio'               => 'https://example.com/audio/abasa.mp3',
                'video'               => 'https://example.com/video/abasa.mp4',
                'image'               => 'https://example.com/image/abasa.jpg',
            ],
            [
                'name'                => 'At-Takwir',
                'arabic_name'         => 'التَكْوِير',
                'bangla_name'         => 'আত-তাকউইর',
                'meaning'             => 'The Overthrowing',
                'english_name'        => 'The Overthrowing',
                'ayat_count'          => '29',
                'type'                => 'Makki',
                'revelation_order'    => '81',
                'rukus'               => '1',
                'place_of_revelation' => 'Mecca',
                'status'              => 'Makki',
                'audio'               => 'https://example.com/audio/takwir.mp3',
                'video'               => 'https://example.com/video/takwir.mp4',
                'image'               => 'https://example.com/image/takwir.jpg',
            ],
            [
                'name'                => 'Al-Infitar',
                'arabic_name'         => 'الانفطار',
                'bangla_name'         => 'আল-ইনফিতার',
                'meaning'             => 'The Splitting Asunder',
                'english_name'        => 'The Splitting Asunder',
                'ayat_count'          => '19',
                'type'                => 'Makki',
                'revelation_order'    => '82',
                'rukus'               => '1',
                'place_of_revelation' => 'Mecca',
                'status'              => 'Makki',
                'audio'               => 'https://example.com/audio/infitar.mp3',
                'video'               => 'https://example.com/video/infitar.mp4',
                'image'               => 'https://example.com/image/infitar.jpg',
            ],
            [
                'name'                => 'Al-Mutaffifin',
                'arabic_name'         => 'الْمُطَفِّفِينَ',
                'bangla_name'         => 'আল-মুতাফ্‌ফিফীন',
                'meaning'             => 'The Defrauding',
                'english_name'        => 'The Defrauding',
                'ayat_count'          => '36',
                'type'                => 'Makki',
                'revelation_order'    => '83',
                'rukus'               => '1',
                'place_of_revelation' => 'Mecca',
                'status'              => 'Makki',
                'audio'               => 'https://example.com/audio/mutaffifin.mp3',
                'video'               => 'https://example.com/video/mutaffifin.mp4',
                'image'               => 'https://example.com/image/mutaffifin.jpg',
            ],
            [
                'name'                => 'Al-Inshiqaq',
                'arabic_name'         => 'الْإِنْشِقَاقُ',
                'bangla_name'         => 'আল-ইনশিকাক',
                'meaning'             => 'The Splitting Asunder',
                'english_name'        => 'The Splitting Asunder',
                'ayat_count'          => '25',
                'type'                => 'Makki',
                'revelation_order'    => '84',
                'rukus'               => '1',
                'place_of_revelation' => 'Mecca',
                'status'              => 'Makki',
                'audio'               => 'https://example.com/audio/inshiqaq.mp3',
                'video'               => 'https://example.com/video/inshiqaq.mp4',
                'image'               => 'https://example.com/image/inshiqaq.jpg',
            ],
            [
                'name'                => 'Al-Burooj',
                'arabic_name'         => 'الْبُرُوجِ',
                'bangla_name'         => 'আল-বুরুজ',
                'meaning'             => 'The Big Stars',
                'english_name'        => 'The Big Stars',
                'ayat_count'          => '22',
                'type'                => 'Makki',
                'revelation_order'    => '85',
                'rukus'               => '1',
                'place_of_revelation' => 'Mecca',
                'status'              => 'Makki',
                'audio'               => 'https://example.com/audio/burooj.mp3',
                'video'               => 'https://example.com/video/burooj.mp4',
                'image'               => 'https://example.com/image/burooj.jpg',
            ],
            [
                'name'                => 'At-Tariq',
                'arabic_name'         => 'الطَّارِقِ',
                'bangla_name'         => 'আত-তারিক',
                'meaning'             => 'The Morning Star',
                'english_name'        => 'The Morning Star',
                'ayat_count'          => '17',
                'type'                => 'Makki',
                'revelation_order'    => '86',
                'rukus'               => '1',
                'place_of_revelation' => 'Mecca',
                'status'              => 'Makki',
                'audio'               => 'https://example.com/audio/tariq.mp3',
                'video'               => 'https://example.com/video/tariq.mp4',
                'image'               => 'https://example.com/image/tariq.jpg',
            ],
            [
                'name'                => 'Al-Ala',
                'arabic_name'         => 'الْأَعْلَىٰ',
                'bangla_name'         => 'আল-আলা',
                'meaning'             => 'The Most High',
                'english_name'        => 'The Most High',
                'ayat_count'          => '19',
                'type'                => 'Makki',
                'revelation_order'    => '87',
                'rukus'               => '1',
                'place_of_revelation' => 'Mecca',
                'status'              => 'Makki',
                'audio'               => 'https://example.com/audio/ala.mp3',
                'video'               => 'https://example.com/video/ala.mp4',
                'image'               => 'https://example.com/image/ala.jpg',
            ],
            [
                'name'                => 'Al-Ghashiya',
                'arabic_name'         => 'الْغَاشِيَةِ',
                'bangla_name'         => 'আল-গাশিয়া',
                'meaning'             => 'The Overwhelming',
                'english_name'        => 'The Overwhelming',
                'ayat_count'          => '26',
                'type'                => 'Makki',
                'revelation_order'    => '88',
                'rukus'               => '1',
                'place_of_revelation' => 'Mecca',
                'status'              => 'Makki',
                'audio'               => 'https://example.com/audio/ghashiya.mp3',
                'video'               => 'https://example.com/video/ghashiya.mp4',
                'image'               => 'https://example.com/image/ghashiya.jpg',
            ],
            [
                'name'                => 'Al-Fajr',
                'arabic_name'         => 'الفَجْرِ',
                'bangla_name'         => 'আল-ফজর',
                'meaning'             => 'The Dawn',
                'english_name'        => 'The Dawn',
                'ayat_count'          => '30',
                'type'                => 'Makki',
                'revelation_order'    => '89',
                'rukus'               => '2',
                'place_of_revelation' => 'Mecca',
                'status'              => 'Makki',
                'audio'               => 'https://example.com/audio/fajr.mp3',
                'video'               => 'https://example.com/video/fajr.mp4',
                'image'               => 'https://example.com/image/fajr.jpg',
            ],
            [
                'name'                => 'Al-Balad',
                'arabic_name'         => 'الْبَلَدِ',
                'bangla_name'         => 'আল-বালাদ',
                'meaning'             => 'The City',
                'english_name'        => 'The City',
                'ayat_count'          => '20',
                'type'                => 'Makki',
                'revelation_order'    => '90',
                'rukus'               => '1',
                'place_of_revelation' => 'Mecca',
                'status'              => 'Makki',
                'audio'               => 'https://example.com/audio/balad.mp3',
                'video'               => 'https://example.com/video/balad.mp4',
                'image'               => 'https://example.com/image/balad.jpg',
            ],
            [
                'name'                => 'Ash-Shams',
                'arabic_name'         => 'الشَّمْسِ',
                'bangla_name'         => 'আশ-শামস',
                'meaning'             => 'The Sun',
                'english_name'        => 'The Sun',
                'ayat_count'          => '15',
                'type'                => 'Makki',
                'revelation_order'    => '91',
                'rukus'               => '1',
                'place_of_revelation' => 'Mecca',
                'status'              => 'Makki',
                'audio'               => 'https://example.com/audio/shams.mp3',
                'video'               => 'https://example.com/video/shams.mp4',
                'image'               => 'https://example.com/image/shams.jpg',
            ],
            [
                'name'                => 'Al-Lail',
                'arabic_name'         => 'اللَّيْلِ',
                'bangla_name'         => 'আল-লাইল',
                'meaning'             => 'The Night',
                'english_name'        => 'The Night',
                'ayat_count'          => '21',
                'type'                => 'Makki',
                'revelation_order'    => '92',
                'rukus'               => '1',
                'place_of_revelation' => 'Mecca',
                'status'              => 'Makki',
                'audio'               => 'https://example.com/audio/lail.mp3',
                'video'               => 'https://example.com/video/lail.mp4',
                'image'               => 'https://example.com/image/lail.jpg',
            ],
            [
                'name'                => 'Ad-Dhuha',
                'arabic_name'         => 'الضُّحَىٰ',
                'bangla_name'         => 'আদ্-দুহা',
                'meaning'             => 'The Morning Hours',
                'english_name'        => 'The Morning Hours',
                'ayat_count'          => '11',
                'type'                => 'Makki',
                'revelation_order'    => '93',
                'rukus'               => '1',
                'place_of_revelation' => 'Mecca',
                'status'              => 'Makki',
                'audio'               => 'https://example.com/audio/dhuha.mp3',
                'video'               => 'https://example.com/video/dhuha.mp4',
                'image'               => 'https://example.com/image/dhuha.jpg',
            ],
            [
                'name'                => 'Ash-Sharh',
                'arabic_name'         => 'الشَّرْحِ',
                'bangla_name'         => 'আশ-শরহ',
                'meaning'             => 'The Relief',
                'english_name'        => 'The Relief',
                'ayat_count'          => '8',
                'type'                => 'Makki',
                'revelation_order'    => '94',
                'rukus'               => '1',
                'place_of_revelation' => 'Mecca',
                'status'              => 'Makki',
                'audio'               => 'https://example.com/audio/sharh.mp3',
                'video'               => 'https://example.com/video/sharh.mp4',
                'image'               => 'https://example.com/image/sharh.jpg',
            ],
            [
                'name'                => 'At-Tin',
                'arabic_name'         => 'التِّينِ',
                'bangla_name'         => 'আত-তিন',
                'meaning'             => 'The Fig',
                'english_name'        => 'The Fig',
                'ayat_count'          => '8',
                'type'                => 'Makki',
                'revelation_order'    => '95',
                'rukus'               => '1',
                'place_of_revelation' => 'Mecca',
                'status'              => 'Makki',
                'audio'               => 'https://example.com/audio/tin.mp3',
                'video'               => 'https://example.com/video/tin.mp4',
                'image'               => 'https://example.com/image/tin.jpg',
            ],
            [
                'name'                => 'Al-Alaq',
                'arabic_name'         => 'الْعَلَقِ',
                'bangla_name'         => 'আল-আলাক',
                'meaning'             => 'The Clot',
                'english_name'        => 'The Clot',
                'ayat_count'          => '19',
                'type'                => 'Makki',
                'revelation_order'    => '96',
                'rukus'               => '1',
                'place_of_revelation' => 'Mecca',
                'status'              => 'Makki',
                'audio'               => 'https://example.com/audio/alaq.mp3',
                'video'               => 'https://example.com/video/alaq.mp4',
                'image'               => 'https://example.com/image/alaq.jpg',
            ],
            [
                'name'                => 'Al-Qadr',
                'arabic_name'         => 'الْقَدْرِ',
                'bangla_name'         => 'আল-কাদর',
                'meaning'             => 'The Power',
                'english_name'        => 'The Power',
                'ayat_count'          => '5',
                'type'                => 'Makki',
                'revelation_order'    => '97',
                'rukus'               => '1',
                'place_of_revelation' => 'Mecca',
                'status'              => 'Makki',
                'audio'               => 'https://example.com/audio/qadr.mp3',
                'video'               => 'https://example.com/video/qadr.mp4',
                'image'               => 'https://example.com/image/qadr.jpg',
            ],
            [
                'name'                => 'Al-Bayyina',
                'arabic_name'         => 'الْبَيِّنَةِ',
                'bangla_name'         => 'আল-বায়িনা',
                'meaning'             => 'The Clear Evidence',
                'english_name'        => 'The Clear Evidence',
                'ayat_count'          => '8',
                'type'                => 'Madani',
                'revelation_order'    => '98',
                'rukus'               => '1',
                'place_of_revelation' => 'Medina',
                'status'              => 'Madani',
                'audio'               => 'https://example.com/audio/bayyina.mp3',
                'video'               => 'https://example.com/video/bayyina.mp4',
                'image'               => 'https://example.com/image/bayyina.jpg',
            ],
            [
                'name'                => 'Al-Zalzala',
                'arabic_name'         => 'الزَّلْزَلَةِ',
                'bangla_name'         => 'আল-য়লজলালা',
                'meaning'             => 'The Earthquake',
                'english_name'        => 'The Earthquake',
                'ayat_count'          => '8',
                'type'                => 'Madani',
                'revelation_order'    => '99',
                'rukus'               => '1',
                'place_of_revelation' => 'Medina',
                'status'              => 'Madani',
                'audio'               => 'https://example.com/audio/zalzala.mp3',
                'video'               => 'https://example.com/video/zalzala.mp4',
                'image'               => 'https://example.com/image/zalzala.jpg',
            ],
            [
                'name'                => 'Al-Adiyaat',
                'arabic_name'         => 'العَادِيَاتِ',
                'bangla_name'         => 'আল-আদিয়াত',
                'meaning'             => 'The Courser',
                'english_name'        => 'The Courser',
                'ayat_count'          => '11',
                'type'                => 'Makki',
                'revelation_order'    => '100',
                'rukus'               => '1',
                'place_of_revelation' => 'Mecca',
                'status'              => 'Makki',
                'audio'               => 'https://example.com/audio/adiyat.mp3',
                'video'               => 'https://example.com/video/adiyat.mp4',
                'image'               => 'https://example.com/image/adiyat.jpg',
            ],
            [
                'name'                => 'Al-Qaria',
                'arabic_name'         => 'القَارِعَةِ',
                'bangla_name'         => 'আল-কারিয়া',
                'meaning'             => 'The Calamity',
                'english_name'        => 'The Calamity',
                'ayat_count'          => '11',
                'type'                => 'Makki',
                'revelation_order'    => '101',
                'rukus'               => '1',
                'place_of_revelation' => 'Mecca',
                'status'              => 'Makki',
                'audio'               => 'https://example.com/audio/qaria.mp3',
                'video'               => 'https://example.com/video/qaria.mp4',
                'image'               => 'https://example.com/image/qaria.jpg',
            ],
            [
                'name'                => 'At-Takaathur',
                'arabic_name'         => 'التَّكَاثُرِ',
                'bangla_name'         => 'আত-তাকাসুর',
                'meaning'             => 'The Rivalry in world increase',
                'english_name'        => 'The Piling Up',
                'ayat_count'          => '8',
                'type'                => 'Makki',
                'revelation_order'    => '102',
                'rukus'               => '1',
                'place_of_revelation' => 'Mecca',
                'status'              => 'Makki',
                'audio'               => 'https://example.com/audio/takaathur.mp3',
                'video'               => 'https://example.com/video/takaathur.mp4',
                'image'               => 'https://example.com/image/takaathur.jpg',
            ],
            [
                'name'                => 'Al-Asr',
                'arabic_name'         => 'الْعَصْرِ',
                'bangla_name'         => 'আল-আসর',
                'meaning'             => 'The Declining Day',
                'english_name'        => 'The Declining Day',
                'ayat_count'          => '3',
                'type'                => 'Makki',
                'revelation_order'    => '103',
                'rukus'               => '1',
                'place_of_revelation' => 'Mecca',
                'status'              => 'Makki',
                'audio'               => 'https://example.com/audio/asr.mp3',
                'video'               => 'https://example.com/video/asr.mp4',
                'image'               => 'https://example.com/image/asr.jpg',
            ],
            [
                'name'                => 'Al-Humazah',
                'arabic_name'         => 'الْهُمَزَةِ',
                'bangla_name'         => 'আল-হুমাজাহ',
                'meaning'             => 'The Traducer',
                'english_name'        => 'The Traducer',
                'ayat_count'          => '9',
                'type'                => 'Makki',
                'revelation_order'    => '104',
                'rukus'               => '1',
                'place_of_revelation' => 'Mecca',
                'status'              => 'Makki',
                'audio'               => 'https://example.com/audio/humazah.mp3',
                'video'               => 'https://example.com/video/humazah.mp4',
                'image'               => 'https://example.com/image/humazah.jpg',
            ],
            [
                'name'                => 'Al-Fil',
                'arabic_name'         => 'الْفِيلِ',
                'bangla_name'         => 'আল-ফিল',
                'meaning'             => 'The Elephant',
                'english_name'        => 'The Elephant',
                'ayat_count'          => '5',
                'type'                => 'Makki',
                'revelation_order'    => '105',
                'rukus'               => '1',
                'place_of_revelation' => 'Mecca',
                'status'              => 'Makki',
                'audio'               => 'https://example.com/audio/fil.mp3',
                'video'               => 'https://example.com/video/fil.mp4',
                'image'               => 'https://example.com/image/fil.jpg',
            ],
            [
                'name'                => 'Quraish',
                'arabic_name'         => 'قُرَيْشٍ',
                'bangla_name'         => 'কুরাইশ',
                'meaning'             => 'Quraish',
                'english_name'        => 'Quraish',
                'ayat_count'          => '4',
                'type'                => 'Makki',
                'revelation_order'    => '106',
                'rukus'               => '1',
                'place_of_revelation' => 'Mecca',
                'status'              => 'Makki',
                'audio'               => 'https://example.com/audio/quraish.mp3',
                'video'               => 'https://example.com/video/quraish.mp4',
                'image'               => 'https://example.com/image/quraish.jpg',
            ],
            [
                'name'                => 'Al-Maun',
                'arabic_name'         => 'الْمَاعُونَ',
                'bangla_name'         => 'আল-মাউন',
                'meaning'             => 'The Small Kindnesses',
                'english_name'        => 'The Small Kindnesses',
                'ayat_count'          => '7',
                'type'                => 'Makki',
                'revelation_order'    => '107',
                'rukus'               => '1',
                'place_of_revelation' => 'Mecca',
                'status'              => 'Makki',
                'audio'               => 'https://example.com/audio/maun.mp3',
                'video'               => 'https://example.com/video/maun.mp4',
                'image'               => 'https://example.com/image/maun.jpg',
            ],
            [
                'name'                => 'Al-Kawthar',
                'arabic_name'         => 'الكَوْثَرِ',
                'bangla_name'         => 'আল-কাউসার',
                'meaning'             => 'The Abundance',
                'english_name'        => 'The Abundance',
                'ayat_count'          => '3',
                'type'                => 'Makki',
                'revelation_order'    => '108',
                'rukus'               => '1',
                'place_of_revelation' => 'Mecca',
                'status'              => 'Makki',
                'audio'               => 'https://example.com/audio/kawthar.mp3',
                'video'               => 'https://example.com/video/kawthar.mp4',
                'image'               => 'https://example.com/image/kawthar.jpg',
            ],
            [
                'name'                => 'Al-Kafirun',
                'arabic_name'         => 'الْكَافِرُونَ',
                'bangla_name'         => 'আল-কাফিরুন',
                'meaning'             => 'The Disbelievers',
                'english_name'        => 'The Disbelievers',
                'ayat_count'          => '6',
                'type'                => 'Makki',
                'revelation_order'    => '109',
                'rukus'               => '1',
                'place_of_revelation' => 'Mecca',
                'status'              => 'Makki',
                'audio'               => 'https://example.com/audio/kafirun.mp3',
                'video'               => 'https://example.com/video/kafirun.mp4',
                'image'               => 'https://example.com/image/kafirun.jpg',
            ],
            [
                'name'                => 'An-Nasr',
                'arabic_name'         => 'النَّصْرِ',
                'bangla_name'         => 'আন-নাসর',
                'meaning'             => 'The Divine Support',
                'english_name'        => 'The Divine Support',
                'ayat_count'          => '3',
                'type'                => 'Madani',
                'revelation_order'    => '110',
                'rukus'               => '1',
                'place_of_revelation' => 'Medina',
                'status'              => 'Madani',
                'audio'               => 'https://example.com/audio/nasr.mp3',
                'video'               => 'https://example.com/video/nasr.mp4',
                'image'               => 'https://example.com/image/nasr.jpg',
            ],
            [
                'name'                => 'Al-Masad',
                'arabic_name'         => 'المَسَدِ',
                'bangla_name'         => 'আল-মাসাদ',
                'meaning'             => 'The Palm Fiber',
                'english_name'        => 'The Palm Fiber',
                'ayat_count'          => '5',
                'type'                => 'Makki',
                'revelation_order'    => '111',
                'rukus'               => '1',
                'place_of_revelation' => 'Mecca',
                'status'              => 'Makki',
                'audio'               => 'https://example.com/audio/masad.mp3',
                'video'               => 'https://example.com/video/masad.mp4',
                'image'               => 'https://example.com/image/masad.jpg',
            ],
            [
                'name'                => 'Al-Ikhlas',
                'arabic_name'         => 'الإِخْلَاصِ',
                'bangla_name'         => 'আল-ইখলাস',
                'meaning'             => 'The Sincerity',
                'english_name'        => 'The Sincerity',
                'ayat_count'          => '4',
                'type'                => 'Makki',
                'revelation_order'    => '112',
                'rukus'               => '1',
                'place_of_revelation' => 'Mecca',
                'status'              => 'Makki',
                'audio'               => 'https://example.com/audio/ikhlas.mp3',
                'video'               => 'https://example.com/video/ikhlas.mp4',
                'image'               => 'https://example.com/image/ikhlas.jpg',
            ],
            [
                'name'                => 'Al-Falaq',
                'arabic_name'         => 'الْفَلَقِ',
                'bangla_name'         => 'আল-ফালাক',
                'meaning'             => 'The Daybreak',
                'english_name'        => 'The Daybreak',
                'ayat_count'          => '5',
                'type'                => 'Makki',
                'revelation_order'    => '113',
                'rukus'               => '1',
                'place_of_revelation' => 'Mecca',
                'status'              => 'Makki',
                'audio'               => 'https://example.com/audio/falaq.mp3',
                'video'               => 'https://example.com/video/falaq.mp4',
                'image'               => 'https://example.com/image/falaq.jpg',
            ],
            [
                'name'                => 'An-Nas',
                'arabic_name'         => 'النَّاسِ',
                'bangla_name'         => 'আন-নাস',
                'meaning'             => 'The Mankind',
                'english_name'        => 'The Mankind',
                'ayat_count'          => '6',
                'type'                => 'Makki',
                'revelation_order'    => '114',
                'rukus'               => '1',
                'place_of_revelation' => 'Mecca',
                'status'              => 'Makki',
                'audio'               => 'https://example.com/audio/nas.mp3',
                'video'               => 'https://example.com/video/nas.mp4',
                'image'               => 'https://example.com/image/nas.jpg',
            ],
        ];

        DB::table('suras')->insert($suras);

    }
}
