version: '3.8'

services:
    app:
        container_name: tohfa-e-ramazan
        hostname: tohfa-e-ramazan
        build:
            context: ./
            target: development
        restart: unless-stopped
        volumes:
            - .:/home/swoole/
            - /home/swoole/vendor
            - ./storage:/home/swoole/storage
            - ./app:/home/swoole/app
        ports:
            - 8888:80
        environment:
            CHOKIDAR_USEPOLLING: 'true'
        user: "swoole:swoole"
        depends_on:
            - db
        networks:
            - ramazan

    db:
        image: mysql:8.0
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: tohfa-e-ramazan
            MYSQL_USER: swoole
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
        volumes:
            - ./mysql:/var/lib/mysql
        networks:
            - ramazan

    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - 8080:80
        environment:
            - PMA_ARBITRARY=1
        networks:
            - ramazan

networks:
    ramazan:
        driver: bridge
